/**
 * avArchiveService.js — data layer for the research archive.
 *
 * 8,632 posts across 14 years. Nothing loads the whole archive: the summary is
 * ~700 bytes, a year index is 17-722 KB and is fetched only when that year is
 * opened, and article bodies come from R2 one at a time.
 *
 * Follows the deliberate shape of blogCatalogService.js — a module-scope
 * in-flight promise so concurrent mounts share one request, and no permanent
 * reference to the parsed result, so a year the user navigated away from
 * becomes garbage-collectable. The difference here is that year indexes are
 * worth keeping while the user browses, so they sit in a small bounded cache
 * rather than being dropped immediately.
 *
 * Generated by scripts/build_av_archive.py.
 */

const YEARS_URL = "/data/av-years.json";
const PREVIEW_URL = "/data/av-preview.json";
const TOPICS_URL = "/data/av-topics.json";
const TOPICS_ALL_URL = "/data/av-topics-all.json";

/** Public read base for article bodies and images, served by av-cdn-worker/. */
export const CDN_BASE = (import.meta.env?.VITE_AV_CDN_BASE || "").replace(/\/$/, "");

const YEAR_CACHE_LIMIT = 4;   // a year index is up to ~722 KB
const POST_CACHE_LIMIT = 20;  // an article body is ~13 KB

let yearsInflight = null;
let previewInflight = null;
let topicsInflight = null;
let topicsAllInflight = null;
const yearCache = new Map();
const postCache = new Map();

function lruSet(map, key, value, limit) {
  map.delete(key);
  map.set(key, value);
  if (map.size > limit) map.delete(map.keys().next().value);
  return value;
}

function lruGet(map, key) {
  if (!map.has(key)) return undefined;
  const value = map.get(key);
  map.delete(key);
  map.set(key, value); // re-insert to mark as most recently used
  return value;
}

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  return res.json();
}

/**
 * Archive summary: every year with its post count. ~700 bytes.
 * @returns {Promise<{version:number,generated:string,cdn:string,total:number,
 *                    years:Array<{y:number,n:number,f:string}>}>}
 */
export function loadYears() {
  if (!yearsInflight) {
    yearsInflight = fetchJson(YEARS_URL).catch((err) => {
      console.error("AV archive: failed to load year summary", err);
      yearsInflight = null; // let the next mount retry
      return { total: 0, years: [], cdn: CDN_BASE };
    });
  }
  return yearsInflight;
}

/** 12 most recent posts, for home-screen surfaces. ~2 KB. */
export function loadPreview() {
  if (!previewInflight) {
    previewInflight = fetchJson(PREVIEW_URL).catch((err) => {
      console.error("AV archive: failed to load preview", err);
      previewInflight = null;
      return [];
    });
  }
  return previewInflight;
}

/**
 * The curated topic tree the Explore Concepts galaxy renders — 9 clusters,
 * ~64 topics, ~430 sample articles. ~47 KB, so it loads whole.
 *
 * Deliberately not derived in the browser from the year indexes: that would
 * mean downloading all 14 of them (~3 MB) and re-deriving a taxonomy that is a
 * build-time editorial decision. See scripts/build_av_topics.py.
 *
 * @returns {Promise<{version:number,total:number,clusters:Array<{
 *   id:string,label:string,color:string,n:number,
 *   topics:Array<{id:string,label:string,n:number,y:string,
 *                 posts:Array<{s:string,t:string}>}>}>}>}
 */
export function loadTopics() {
  if (!topicsInflight) {
    topicsInflight = fetchJson(TOPICS_URL).catch((err) => {
      console.error("AV archive: failed to load topic tree", err);
      topicsInflight = null; // let the next mount retry
      return { total: 0, clusters: [] };
    });
  }
  return topicsInflight;
}

/**
 * Every article in the topic tree — 8,167 of them, 912 KB. Same clusters and
 * topics as loadTopics(), addressed by the same ids, so the caller merges the
 * post lists onto the tree it already has.
 *
 * Only fetched when the galaxy's ALL switch is turned on. Posts arrive as
 * `[slug, title]` pairs rather than objects: at this row count the key names
 * would be a third of the file.
 *
 * @returns {Promise<{clusters:Array<{id:string,
 *   topics:Array<{id:string,posts:Array<[string,string]>}>}>}>}
 */
export function loadAllTopics() {
  if (!topicsAllInflight) {
    topicsAllInflight = fetchJson(TOPICS_ALL_URL).catch((err) => {
      console.error("AV archive: failed to load full topic tree", err);
      topicsAllInflight = null;
      return { clusters: [] };
    });
  }
  return topicsAllInflight;
}

/**
 * One year's post index, with categories already expanded onto each post.
 *
 * The on-disk format interns category strings and refers to them by index —
 * that is what keeps 2024 at 722 KB instead of ~1.4 MB. Expanding here means
 * no component has to know about the encoding.
 *
 * @param {number|string} year
 * @returns {Promise<{year:number,categories:string[],posts:Array<object>}>}
 */
export function loadYear(year) {
  const key = String(year);
  const cached = lruGet(yearCache, key);
  if (cached) return cached;

  const promise = fetchJson(`/data/av-${key}.json`)
    .then((data) => ({
      year: data.y,
      categories: data.categories || [],
      posts: (data.posts || []).map((p) => ({
        slug: p.s,
        title: p.t,
        month: p.d,
        categories: (p.c || []).map((i) => data.categories[i]).filter(Boolean),
        excerpt: p.x || "",
        hasHero: p.h === 1,
        imageCount: p.n || 0,
        hero: p.h === 1 ? `${CDN_BASE}/${data.y}/img/${p.s}/hero.webp` : null,
      })),
    }))
    .catch((err) => {
      console.error(`AV archive: failed to load ${key}`, err);
      yearCache.delete(key);
      return { year: Number(year), categories: [], posts: [] };
    });

  return lruSet(yearCache, key, promise, YEAR_CACHE_LIMIT);
}

/**
 * An article body as markdown. Image paths inside are root-relative
 * (`/2024/img/…`) — call resolveImage() or pass the CDN base to the renderer.
 *
 * @param {string} slug e.g. "2024-12-multi-vector-chatbot"
 * @returns {Promise<string>} markdown, or "" if unavailable
 */
export function loadPost(slug) {
  const cached = lruGet(postCache, slug);
  if (cached) return cached;

  const year = slug.slice(0, 4);
  const promise = fetch(`${CDN_BASE}/${year}/md/${slug}.md`)
    .then((res) => {
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res.text();
    })
    .catch((err) => {
      console.error(`AV archive: failed to load post ${slug}`, err);
      postCache.delete(slug);
      return "";
    });

  return lruSet(postCache, slug, promise, POST_CACHE_LIMIT);
}

/**
 * Turn a root-relative image path from the markdown into a full URL.
 * Kept as a function rather than baked into the files at build time so that
 * moving to a custom domain is an env change, not a rebuild of 8,632 posts.
 */
export function resolveImage(src) {
  if (!src) return src;
  if (/^(https?:)?\/\//i.test(src) || src.startsWith("data:")) return src;
  return `${CDN_BASE}${src.startsWith("/") ? "" : "/"}${src}`;
}

/**
 * Filter one year's posts. Search covers title, excerpt and categories —
 * deliberately not article bodies, which are 127 MB and not something a
 * browser should be asked to index.
 *
 * @param {Array<object>} posts   from loadYear()
 * @param {{query?:string, categories?:string[], month?:string}} filters
 */
export function filterPosts(posts, { query = "", categories = [], month = "" } = {}) {
  const q = query.trim().toLowerCase();
  const wanted = categories.length ? new Set(categories) : null;

  return posts.filter((post) => {
    if (month && post.month !== month) return false;
    if (wanted && !post.categories.some((c) => wanted.has(c))) return false;
    if (!q) return true;
    return (
      post.title.toLowerCase().includes(q) ||
      post.excerpt.toLowerCase().includes(q) ||
      post.categories.some((c) => c.toLowerCase().includes(q))
    );
  });
}

/** Distinct months present in a year's posts, newest first. */
export function monthsOf(posts) {
  return [...new Set(posts.map((p) => p.month).filter(Boolean))].sort().reverse();
}

/** Category counts for a set of posts, most common first. */
export function categoryCounts(posts) {
  const counts = new Map();
  for (const post of posts) {
    for (const category of post.categories) {
      counts.set(category, (counts.get(category) || 0) + 1);
    }
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]);
}

/** Human label for a "YYYY-MM" month key. */
const MONTH_NAMES = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];
export function monthLabel(month) {
  if (!month) return "";
  const [year, mm] = month.split("-");
  return `${MONTH_NAMES[Number(mm) - 1] || mm} ${year}`;
}
