/**
 * blogCatalogService.js — runtime loader for the blog catalog.
 *
 * This data used to live in `src/data/blogData.js` and was imported statically by
 * three components, two of which (FeatureHome, IntelligenceHub) are home screens.
 * That put a 2.9 MB chunk on the critical path of the first screen a user sees —
 * downloaded, parsed, and turned into live JS objects before anything painted.
 *
 * Fetching it instead has two effects:
 *   1. It leaves the bundle graph entirely, so it is no longer part of any chunk.
 *   2. It becomes garbage-collectable. A static ES module import is reachable for
 *      the lifetime of the page; a fetched object is released when the last
 *      component holding it unmounts, which matters in an app with no page reloads.
 *
 * Regenerated by scripts/process_blogs.py.
 */

const CATALOG_URL = '/data/blog-catalog.json';

// Module-scope promise so concurrent mounts share one request. This intentionally
// does NOT hold the parsed result itself — see the note above about GC.
let inflight = null;

/** @returns {Promise<Record<string, Array<{title,url,description}>>>} */
export function loadBlogCatalog() {
  if (!inflight) {
    inflight = fetch(CATALOG_URL)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .catch((err) => {
        console.error('Failed to load blog catalog:', err);
        inflight = null; // allow a retry on the next mount
        return {};
      });
  }
  return inflight;
}

/** Flatten the catalog into the year-tagged article list most callers want. */
export function flattenCatalog(catalog) {
  return Object.entries(catalog || {}).flatMap(([year, articles]) =>
    (articles || []).map((article) => ({ ...article, year }))
  );
}

/** Archive years, newest first, with "Featured" pinned to the top. */
export function sortedYears(catalog) {
  return Object.keys(catalog || {}).sort((a, b) => {
    if (a === 'Featured') return -1;
    if (b === 'Featured') return 1;
    return Number(b) - Number(a);
  });
}
