import { createDefaultEdge } from '@/constants';
import { NodeType } from '@/lib/types';
import { createTemplateRegistry, type TemplateRegistry } from './registry';
import type { TemplateManifest } from './types';
import {
  createArchitectureNode,
  createAssetNode,
  createFlowNode,
  createMindmapNode,
  createTemplate,
} from './templateFactories';

export const STARTER_TEMPLATE_MANIFESTS: TemplateManifest[] = [
  createTemplate(
    'incident-response-command-flow',
    'Incident Response Command Flow',
    'A production incident flow with severity triage, response ownership, external comms, and follow-up work.',
    'flowchart',
    ['incident', 'sre', 'operations', 'oncall'],
    [
      createFlowNode('irc-1', NodeType.START, 'Pager Alert Triggered', 0, 0, 'red', {
        subLabel: 'Latency, errors, or saturation threshold breached',
      }),
      createFlowNode('irc-2', NodeType.PROCESS, 'Validate Signal and Blast Radius', 0, 150, 'slate', {
        subLabel: 'Correlate dashboards, logs, deploys, and region impact',
      }),
      createFlowNode('irc-3', NodeType.DECISION, 'Customer Impact Confirmed?', 0, 340, 'amber', {
        subLabel: 'Severity gate for escalation and comms',
      }),
      createFlowNode('irc-4', NodeType.PROCESS, 'Open SEV Channel and Assign Roles', -260, 560, 'red', {
        subLabel: 'Incident commander, comms lead, domain owner',
      }),
      createFlowNode('irc-5', NodeType.PROCESS, 'Mitigate in Service', 260, 560, 'blue', {
        subLabel: 'Rollback, feature flag, failover, or circuit breaker',
      }),
      createFlowNode('irc-6', NodeType.PROCESS, 'Publish Status Update', -260, 760, 'violet', {
        subLabel: 'Internal stakeholders and external status page',
      }),
      createFlowNode('irc-7', NodeType.DECISION, 'Service Stable?', 260, 760, 'amber', {
        subLabel: 'Error rate normal, queue drained, customer path healthy',
      }),
      createFlowNode('irc-8', NodeType.PROCESS, 'Escalate to Partner or Infra Team', 520, 940, 'orange', {
        subLabel: 'Cloud provider, database team, or network owner',
      }),
      createFlowNode('irc-9', NodeType.PROCESS, 'Capture Timeline and Actions', 0, 1120, 'slate', {
        subLabel: 'Pin logs, commands, decision points, and owners',
      }),
      createFlowNode('irc-10', NodeType.END, 'Postmortem Scheduled', 0, 1320, 'emerald', {
        subLabel: 'Corrective actions tracked with due dates',
      }),
      createFlowNode('irc-note', NodeType.ANNOTATION, 'Replace alerts, severities, and roles with your team workflow.', -430, 1120, 'yellow', {
        subLabel: 'Best first edit: update the escalation channel and incident roles',
      }),
    ],
    [
      createDefaultEdge('irc-1', 'irc-2', 'Acknowledge within 5 min'),
      createDefaultEdge('irc-2', 'irc-3', 'Triage complete'),
      createDefaultEdge('irc-3', 'irc-4', 'Yes, customer-facing'),
      createDefaultEdge('irc-3', 'irc-5', 'No, contained'),
      createDefaultEdge('irc-4', 'irc-6', 'SEV process live'),
      createDefaultEdge('irc-5', 'irc-7', 'Mitigation applied'),
      createDefaultEdge('irc-6', 'irc-9', 'Comms cadence set'),
      createDefaultEdge('irc-7', 'irc-9', 'Yes'),
      createDefaultEdge('irc-7', 'irc-8', 'No'),
      createDefaultEdge('irc-8', 'irc-9', 'Additional support engaged'),
      createDefaultEdge('irc-9', 'irc-10', 'Follow-up assigned'),
      createDefaultEdge('irc-note', 'irc-9', 'edit guidance'),
    ],
    {
      audience: 'developers',
      useCase: 'Run a real production incident with clear roles and handoffs',
      launchPriority: 10,
      featured: true,
      difficulty: 'intermediate',
      outcome: 'Leaves you with a reusable incident runbook your on-call team can adapt immediately.',
      replacementHints: ['Alert source', 'Severity names', 'Escalation channel', 'Owner roles'],
    }
  ),
  createTemplate(
    'production-release-train',
    'Production Release Train',
    'A delivery workflow from merge readiness through canary checks, approvals, and rollback handling.',
    'flowchart',
    ['release', 'delivery', 'devops', 'platform'],
    [
      createFlowNode('prt-1', NodeType.START, 'Merge Queue Ready', 0, 0, 'slate', {
        subLabel: 'Protected branch and release candidate tagged',
      }),
      createFlowNode('prt-2', NodeType.PROCESS, 'Run Build, Test, and Security Gates', 0, 150, 'blue', {
        subLabel: 'Unit, integration, lint, image scan, and migration checks',
      }),
      createFlowNode('prt-3', NodeType.DECISION, 'Release Candidate Healthy?', 0, 340, 'amber', {
        subLabel: 'All gates green and rollback package available',
      }),
      createFlowNode('prt-4', NodeType.PROCESS, 'Publish Artifact and Release Notes', 260, 560, 'violet', {
        subLabel: 'Versioned image, changelog, and rollout checklist',
      }),
      createFlowNode('prt-5', NodeType.PROCESS, 'Reject and Notify Owning Team', -260, 560, 'red', {
        subLabel: 'Failure summary to Slack and issue tracker',
      }),
      createFlowNode('prt-6', NodeType.PROCESS, 'Deploy Canary Slice', 260, 760, 'blue', {
        subLabel: 'Low-traffic tenant or single region rollout',
      }),
      createFlowNode('prt-7', NodeType.DECISION, 'Canary Metrics Within Guardrails?', 260, 960, 'amber', {
        subLabel: 'Latency, error rate, saturation, and business KPI check',
      }),
      createFlowNode('prt-8', NodeType.PROCESS, 'Promote to General Availability', 0, 1160, 'emerald', {
        subLabel: 'Progressive rollout complete and ops handoff posted',
      }),
      createFlowNode('prt-9', NodeType.PROCESS, 'Rollback and Freeze Train', 520, 1160, 'red', {
        subLabel: 'Revert artifact and suspend downstream deploys',
      }),
      createFlowNode('prt-note', NodeType.ANNOTATION, 'Swap in your actual environments, guardrails, and approval steps.', -420, 960, 'yellow', {
        subLabel: 'Best first edit: canary policy and release owner',
      }),
    ],
    [
      createDefaultEdge('prt-1', 'prt-2', 'Start train'),
      createDefaultEdge('prt-2', 'prt-3', 'All checks finished'),
      createDefaultEdge('prt-3', 'prt-4', 'Yes'),
      createDefaultEdge('prt-3', 'prt-5', 'No'),
      createDefaultEdge('prt-4', 'prt-6', 'Artifact signed'),
      createDefaultEdge('prt-6', 'prt-7', 'Canary live'),
      createDefaultEdge('prt-7', 'prt-8', 'Yes'),
      createDefaultEdge('prt-7', 'prt-9', 'No'),
      createDefaultEdge('prt-note', 'prt-7', 'edit guardrails'),
    ],
    {
      audience: 'developers',
      useCase: 'Show how software moves from merge to safe production rollout',
      launchPriority: 9,
      featured: true,
      difficulty: 'intermediate',
      outcome: 'Creates a concrete release flow that teams can edit for their CI/CD and approval model.',
      replacementHints: ['Build gates', 'Artifact name', 'Canary environment', 'Approval owner'],
    }
  ),
  createTemplate(
    'customer-support-ai-escalation',
    'Customer Support AI Escalation',
    'A support workflow with AI triage, confidence checks, human routing, and follow-up quality loops.',
    'flowchart',
    ['support', 'ai', 'operations', 'customer'],
    [
      createFlowNode('csa-1', NodeType.START, 'Ticket Submitted', 0, 0, 'blue', {
        subLabel: 'Email, chat, or in-app request enters the queue',
      }),
      createFlowNode('csa-2', NodeType.PROCESS, 'Classify Intent and Account Tier', 0, 150, 'violet', {
        subLabel: 'LLM draft plus account context and SLA',
      }),
      createFlowNode('csa-3', NodeType.DECISION, 'Confidence Above Auto-Resolve Threshold?', 0, 340, 'amber', {
        subLabel: 'Use policy and quality gate, not model score alone',
      }),
      createFlowNode('csa-4', NodeType.PROCESS, 'Send Guided Resolution', -260, 560, 'emerald', {
        subLabel: 'Knowledge base answer with next-step checklist',
      }),
      createFlowNode('csa-5', NodeType.PROCESS, 'Route to Specialist Queue', 260, 560, 'blue', {
        subLabel: 'Billing, product, security, or infra ownership',
      }),
      createFlowNode('csa-6', NodeType.DECISION, 'Customer Replied or Reopened?', -260, 760, 'amber', {
        subLabel: 'Measure whether self-service actually solved the case',
      }),
      createFlowNode('csa-7', NodeType.PROCESS, 'Human Triage With Context Pack', 260, 760, 'slate', {
        subLabel: 'Conversation summary, product events, and suggested actions',
      }),
      createFlowNode('csa-8', NodeType.PROCESS, 'Escalate Engineering Issue', 520, 960, 'orange', {
        subLabel: 'Bug, outage, or product gap requires internal owner',
      }),
      createFlowNode('csa-9', NodeType.END, 'Case Closed and Feedback Logged', 0, 1160, 'emerald', {
        subLabel: 'Resolution reason and training signal captured',
      }),
      createFlowNode('csa-note', NodeType.ANNOTATION, 'Replace routing teams, thresholds, and escalation rules with your support org.', -430, 1160, 'yellow', {
        subLabel: 'Best first edit: queues, SLA promises, and resolution policy',
      }),
    ],
    [
      createDefaultEdge('csa-1', 'csa-2', 'Ticket ingested'),
      createDefaultEdge('csa-2', 'csa-3', 'Draft ready'),
      createDefaultEdge('csa-3', 'csa-4', 'Yes'),
      createDefaultEdge('csa-3', 'csa-5', 'No'),
      createDefaultEdge('csa-4', 'csa-6', 'Response sent'),
      createDefaultEdge('csa-6', 'csa-9', 'No, resolved'),
      createDefaultEdge('csa-6', 'csa-7', 'Yes, still blocked'),
      createDefaultEdge('csa-5', 'csa-7', 'Specialist owns case'),
      createDefaultEdge('csa-7', 'csa-8', 'Engineering needed'),
      createDefaultEdge('csa-7', 'csa-9', 'Handled in support'),
      createDefaultEdge('csa-8', 'csa-9', 'Bug owner assigned'),
      createDefaultEdge('csa-note', 'csa-9', 'edit policy'),
    ],
    {
      audience: 'builders',
      useCase: 'Map a modern support workflow with AI and human fallback',
      launchPriority: 8,
      featured: true,
      difficulty: 'intermediate',
      outcome: 'Gives support teams an editable operating flow instead of a vague AI automation sketch.',
      replacementHints: ['Ticket channels', 'Specialist queues', 'Confidence threshold', 'Escalation rules'],
    }
  ),
  createTemplate(
    'c4-system-context',
    'C4 System Context',
    'A context diagram showing users, surrounding systems, delivery surfaces, and the main product boundary.',
    'architecture',
    ['architecture', 'c4', 'documentation'],
    [
      createArchitectureNode('c4-user', 'Platform Engineer', 'person', 'User', 'blue', -420, 220, 'Uses the product to create and share diagrams'),
      createArchitectureNode('c4-team', 'Product Team', 'person', 'Users', 'cyan', -420, 420, 'Maintains templates, docs, and release flow'),
      createArchitectureNode('c4-core', 'OpenFlow Workspace', 'system', 'Box', 'slate', 40, 320, 'Primary system boundary'),
      createArchitectureNode('c4-auth', 'Identity Provider', 'system', 'ShieldCheck', 'violet', 480, 120, 'Authentication and access policy'),
      createArchitectureNode('c4-docs', 'Documentation Site', 'container', 'BookOpen', 'emerald', 480, 320, 'Embeds guides, examples, and exported diagrams'),
      createArchitectureNode('c4-ci', 'Release Pipeline', 'container', 'GitBranch', 'orange', 480, 520, 'Builds, tests, and publishes changes'),
      createFlowNode('c4-note', NodeType.ANNOTATION, 'Swap the central system and surrounding actors to match your product boundary.', 30, 600, 'yellow', {
        subLabel: 'Best first edit: central system label, users, and adjacent systems',
      }),
    ],
    [
      createDefaultEdge('c4-user', 'c4-core', 'creates diagrams'),
      createDefaultEdge('c4-team', 'c4-core', 'curates templates'),
      createDefaultEdge('c4-core', 'c4-auth', 'delegates sign-in'),
      createDefaultEdge('c4-core', 'c4-docs', 'publishes assets'),
      createDefaultEdge('c4-ci', 'c4-core', 'deploys releases'),
      createDefaultEdge('c4-note', 'c4-core', 'replace context'),
    ],
    {
      audience: 'developers',
      useCase: 'Explain what your system is, who uses it, and what it depends on',
      launchPriority: 10,
      featured: true,
      difficulty: 'starter',
      outcome: 'Produces a credible context diagram that is ready for internal docs and design reviews.',
      replacementHints: ['Central system', 'Primary users', 'External systems', 'Key integrations'],
    }
  ),
  createTemplate(
    'c4-container-architecture',
    'C4 Container Architecture',
    'A container-level architecture with application surfaces, async workers, storage, and observability touchpoints.',
    'architecture',
    ['architecture', 'c4', 'containers', 'platform'],
    [
      createArchitectureNode('c4c-web', 'Web App', 'container', 'Monitor', 'blue', -260, 80, 'User-facing product UI'),
      createArchitectureNode('c4c-api', 'API Service', 'container', 'ServerCog', 'slate', 60, 80, 'Primary application backend'),
      createArchitectureNode('c4c-worker', 'Background Worker', 'container', 'Package', 'violet', 380, 80, 'Async jobs and retries'),
      createArchitectureNode('c4c-queue', 'Job Queue', 'queue', 'ListTree', 'orange', 380, 320, 'Buffers outbound and long-running tasks'),
      createArchitectureNode('c4c-db', 'Postgres', 'database_container', 'Database', 'emerald', 60, 320, 'Transactional system of record'),
      createArchitectureNode('c4c-cache', 'Redis Cache', 'cache', 'Layers3', 'cyan', -260, 320, 'Sessions and hot reads'),
      createArchitectureNode('c4c-obs', 'Observability Stack', 'service', 'Activity', 'red', 60, 560, 'Logs, traces, and alerts'),
      createFlowNode('c4c-note', NodeType.ANNOTATION, 'Rename containers to match your codebase and deployment units.', -260, 560, 'yellow', {
        subLabel: 'Best first edit: services, storage, and queue ownership',
      }),
    ],
    [
      createDefaultEdge('c4c-web', 'c4c-api', 'HTTPS'),
      createDefaultEdge('c4c-api', 'c4c-db', 'reads/writes'),
      createDefaultEdge('c4c-api', 'c4c-cache', 'hot path cache'),
      createDefaultEdge('c4c-api', 'c4c-queue', 'enqueue jobs'),
      createDefaultEdge('c4c-worker', 'c4c-queue', 'consume'),
      createDefaultEdge('c4c-worker', 'c4c-db', 'update records'),
      createDefaultEdge('c4c-api', 'c4c-obs', 'emit traces'),
      createDefaultEdge('c4c-worker', 'c4c-obs', 'job metrics'),
      createDefaultEdge('c4c-note', 'c4c-api', 'replace containers'),
    ],
    {
      audience: 'developers',
      useCase: 'Show the main application containers and how they interact',
      launchPriority: 9,
      featured: false,
      difficulty: 'intermediate',
      outcome: 'Creates a container diagram that engineering teams can personalize without redrawing structure from scratch.',
      replacementHints: ['Service names', 'Queue tech', 'Primary datastore', 'Observability tooling'],
    }
  ),
  createTemplate(
    'edge-security-zero-trust-access',
    'Edge Security and Zero-Trust Access',
    'A perimeter and private-access architecture covering public ingress, policy checks, service routing, and operator access.',
    'architecture',
    ['architecture', 'network', 'security', 'zero-trust'],
    [
      createArchitectureNode('esz-dns', 'Public DNS', 'dns', 'Globe2', 'lime', -360, 220, 'Traffic entry point and record management'),
      createArchitectureNode('esz-edge', 'CDN and Edge Termination', 'cdn', 'Globe', 'violet', -60, 220, 'Caching, TLS, and bot controls'),
      createArchitectureNode('esz-policy', 'WAF and Access Policy', 'firewall', 'Shield', 'red', 240, 220, 'Policy checks for public and admin traffic'),
      createArchitectureNode('esz-gateway', 'Application Gateway', 'load_balancer', 'Scale', 'orange', 540, 220, 'Routes verified traffic to private services'),
      createArchitectureNode('esz-app', 'Private Application Services', 'service', 'ServerCog', 'blue', 860, 120, 'Business APIs and frontends'),
      createArchitectureNode('esz-admin', 'Operator Access Broker', 'service', 'Cable', 'cyan', 860, 320, 'Short-lived admin access and session policy'),
      createArchitectureNode('esz-logs', 'Security Logging', 'service', 'Activity', 'slate', 540, 480, 'Audit trail and alerting'),
      createFlowNode('esz-note', NodeType.ANNOTATION, 'Replace policy names, admin path, and trust boundaries with your environment.', 200, 640, 'yellow', {
        subLabel: 'Best first edit: ingress controls, operator path, and audit sinks',
      }),
    ],
    [
      createDefaultEdge('esz-dns', 'esz-edge', 'resolve traffic'),
      createDefaultEdge('esz-edge', 'esz-policy', 'forward HTTPS'),
      createDefaultEdge('esz-policy', 'esz-gateway', 'allow public path'),
      createDefaultEdge('esz-gateway', 'esz-app', 'route app traffic'),
      createDefaultEdge('esz-admin', 'esz-app', 'admin session'),
      createDefaultEdge('esz-policy', 'esz-logs', 'write security events'),
      createDefaultEdge('esz-admin', 'esz-logs', 'session audit'),
      createDefaultEdge('esz-note', 'esz-policy', 'replace boundaries'),
    ],
    {
      audience: 'developers',
      useCase: 'Explain perimeter security and controlled private access without overcomplicating the diagram',
      launchPriority: 8,
      featured: true,
      difficulty: 'intermediate',
      outcome: 'Gives teams a security architecture starter with real access and audit concepts already mapped.',
      replacementHints: ['Ingress controls', 'Gateway name', 'Admin access path', 'Audit destination'],
    }
  ),
  createTemplate(
    'aws-event-driven-saas-platform',
    'AWS Event-Driven SaaS Platform',
    'An AWS starter with API ingress, tenant-aware async processing, orchestration, persistence, and alerting.',
    'aws',
    ['aws', 'serverless', 'saas', 'events'],
    [
      createAssetNode('aws-saas-1', 'aws', 'API Gateway', 'Networking Content Delivery', 'networking-content-delivery-api-gateway', -220, 0),
      createAssetNode('aws-saas-2', 'aws', 'Lambda API', 'Compute', 'compute-lambda', 0, 0),
      createAssetNode('aws-saas-3', 'aws', 'EventBridge', 'Application Integration', 'application-integration-eventbridge', 220, 0),
      createAssetNode('aws-saas-4', 'aws', 'SQS Work Queue', 'Application Integration', 'application-integration-simple-queue-service', 220, 240),
      createAssetNode('aws-saas-5', 'aws', 'Step Functions', 'Application Integration', 'application-integration-step-functions', 460, 240),
      createAssetNode('aws-saas-6', 'aws', 'DynamoDB Tenant Data', 'Databases', 'databases-dynamodb', 0, 240),
      createAssetNode('aws-saas-7', 'aws', 'SES Customer Notices', 'Business Applications', 'business-applications-simple-email-service', 460, 480),
      createAssetNode('aws-saas-8', 'aws', 'CloudWatch Alerts', 'Management Tools', 'management-tools-cloudwatch', -220, 480),
      createFlowNode('aws-saas-note', NodeType.ANNOTATION, 'Replace tenant events, storage, and async handlers with your own platform flow.', 80, 660, 'yellow', {
        subLabel: 'Best first edit: tenant event names, queue consumers, and customer notifications',
      }),
    ],
    [
      createDefaultEdge('aws-saas-1', 'aws-saas-2', 'tenant request'),
      createDefaultEdge('aws-saas-2', 'aws-saas-3', 'emit domain event'),
      createDefaultEdge('aws-saas-2', 'aws-saas-6', 'write command state'),
      createDefaultEdge('aws-saas-3', 'aws-saas-4', 'fan out work'),
      createDefaultEdge('aws-saas-4', 'aws-saas-5', 'process async workflow'),
      createDefaultEdge('aws-saas-5', 'aws-saas-6', 'persist result'),
      createDefaultEdge('aws-saas-5', 'aws-saas-7', 'notify customer'),
      createDefaultEdge('aws-saas-2', 'aws-saas-8', 'app metrics'),
      createDefaultEdge('aws-saas-5', 'aws-saas-8', 'workflow alarms'),
      createDefaultEdge('aws-saas-note', 'aws-saas-5', 'replace workflow'),
    ],
    {
      audience: 'developers',
      useCase: 'Describe an event-driven AWS application without starting from a blank icon board',
      launchPriority: 10,
      featured: true,
      difficulty: 'intermediate',
      outcome: 'Provides a cloud diagram that already contains ingress, persistence, async orchestration, and notifications.',
      replacementHints: ['API name', 'Domain events', 'Queue consumers', 'Notification path'],
      previewVariant: 'asset-rich',
    }
  ),
  createTemplate(
    'aws-container-platform-observability',
    'AWS Container Platform with Observability',
    'A container delivery platform showing build, registry, runtime, edge traffic, cache, and operational visibility.',
    'aws',
    ['aws', 'containers', 'observability', 'platform'],
    [
      createAssetNode('aws-cont-1', 'aws', 'CodeBuild', 'Developer Tools', 'developer-tools-codebuild', -220, 0),
      createAssetNode('aws-cont-2', 'aws', 'ECR', 'Containers', 'containers-elastic-container-registry', 0, 0),
      createAssetNode('aws-cont-3', 'aws', 'ECS Service', 'Containers', 'containers-elastic-container-service', 220, 0),
      createAssetNode('aws-cont-4', 'aws', 'Application Load Balancer', 'Networking Content Delivery', 'networking-content-delivery-elastic-load-balancing', 220, 240),
      createAssetNode('aws-cont-5', 'aws', 'CloudWatch', 'Management Tools', 'management-tools-cloudwatch', 0, 240),
      createAssetNode('aws-cont-6', 'aws', 'ElastiCache', 'Databases', 'databases-elasticache', 460, 240),
      createAssetNode('aws-cont-7', 'aws', 'X-Ray', 'Developer Tools', 'developer-tools-x-ray', 0, 480),
      createFlowNode('aws-cont-note', NodeType.ANNOTATION, 'Use this to map real runtime dependencies, not just deployment order.', 160, 660, 'yellow', {
        subLabel: 'Best first edit: runtime service name, cache usage, and alerting thresholds',
      }),
    ],
    [
      createDefaultEdge('aws-cont-1', 'aws-cont-2', 'publish image'),
      createDefaultEdge('aws-cont-2', 'aws-cont-3', 'deploy task definition'),
      createDefaultEdge('aws-cont-3', 'aws-cont-4', 'serve traffic'),
      createDefaultEdge('aws-cont-3', 'aws-cont-5', 'emit metrics'),
      createDefaultEdge('aws-cont-3', 'aws-cont-6', 'cache reads'),
      createDefaultEdge('aws-cont-3', 'aws-cont-7', 'trace requests'),
      createDefaultEdge('aws-cont-note', 'aws-cont-3', 'replace runtime'),
    ],
    {
      audience: 'developers',
      useCase: 'Map a container platform with both delivery and operational visibility',
      launchPriority: 8,
      featured: false,
      difficulty: 'intermediate',
      outcome: 'Helps platform teams explain the path from build to runtime plus the observability they rely on.',
      replacementHints: ['Runtime service', 'Edge entry', 'Cache dependency', 'Observability stack'],
      previewVariant: 'asset-rich',
    }
  ),
  createTemplate(
    'azure-ai-application-platform',
    'Azure AI Application Platform',
    'An Azure-based AI product stack with model access, application services, retrieval, and monitoring.',
    'azure',
    ['azure', 'ai', 'application', 'platform'],
    [
      createAssetNode('az-ai-1', 'azure', 'Azure OpenAI', 'Ai Plus Machine Learning', 'ai-plus-machine-learning-azure-openai', 0, 0),
      createAssetNode('az-ai-2', 'azure', 'Azure AI Studio', 'Ai Plus Machine Learning', 'ai-plus-machine-learning-ai-studio', -240, 220),
      createAssetNode('az-ai-3', 'azure', 'App Services', 'App Services', 'app-services-app-services', 240, 220),
      createAssetNode('az-ai-4', 'azure', 'Cognitive Search', 'Ai Plus Machine Learning', 'ai-plus-machine-learning-cognitive-search', 0, 440),
      createAssetNode('az-ai-5', 'azure', 'Application Insights', 'Management Plus Governance', 'management-plus-governance-application-insights', 240, 660),
      createFlowNode('az-ai-note', NodeType.ANNOTATION, 'Replace the AI workflow, app surface, and retrieval stack with your product architecture.', -220, 660, 'yellow', {
        subLabel: 'Best first edit: model endpoint, app tier, and retrieval source',
      }),
    ],
    [
      createDefaultEdge('az-ai-2', 'az-ai-1', 'prompt orchestration'),
      createDefaultEdge('az-ai-1', 'az-ai-3', 'model responses'),
      createDefaultEdge('az-ai-3', 'az-ai-4', 'retrieve context'),
      createDefaultEdge('az-ai-3', 'az-ai-5', 'app telemetry'),
      createDefaultEdge('az-ai-note', 'az-ai-3', 'replace app flow'),
    ],
    {
      audience: 'developers',
      useCase: 'Explain an Azure AI application with model, app, search, and telemetry paths',
      launchPriority: 8,
      featured: true,
      difficulty: 'starter',
      outcome: 'Gives teams a realistic Azure AI architecture starter that is simple enough to customize quickly.',
      replacementHints: ['Model endpoint', 'App tier', 'Retrieval source', 'Monitoring setup'],
      previewVariant: 'asset-rich',
    }
  ),
  createTemplate(
    'cncf-gitops-delivery-platform',
    'CNCF GitOps Delivery Platform',
    'A GitOps platform loop with catalog, packaging, policy, network, identity, and cost signals.',
    'cncf',
    ['cncf', 'gitops', 'platform', 'delivery'],
    [
      createAssetNode('cncf-go-1', 'cncf', 'Backstage', 'Projects', 'projects-backstage', 0, 0),
      createAssetNode('cncf-go-2', 'cncf', 'Helm', 'Projects', 'projects-helm', -220, 220),
      createAssetNode('cncf-go-3', 'cncf', 'Cilium', 'Projects', 'projects-cilium', -220, 460),
      createAssetNode('cncf-go-4', 'cncf', 'SPIRE', 'Projects', 'projects-spire', 220, 460),
      createAssetNode('cncf-go-5', 'cncf', 'OpenCost', 'Projects', 'projects-opencost', 220, 220),
      createAssetNode('cncf-go-6', 'cncf', 'Artifact Hub', 'Projects', 'projects-artifacthub', 0, 700),
      createFlowNode('cncf-go-note', NodeType.ANNOTATION, 'Map the actual golden path, delivery controls, and platform telemetry used by your cluster platform.', 40, 900, 'yellow', {
        subLabel: 'Best first edit: portal entrypoint, policy engine, and cost/identity controls',
      }),
    ],
    [
      createDefaultEdge('cncf-go-1', 'cncf-go-2', 'package templates'),
      createDefaultEdge('cncf-go-2', 'cncf-go-3', 'deploy network policy'),
      createDefaultEdge('cncf-go-2', 'cncf-go-4', 'workload identity'),
      createDefaultEdge('cncf-go-3', 'cncf-go-5', 'runtime cost signals'),
      createDefaultEdge('cncf-go-4', 'cncf-go-6', 'signed releases'),
      createDefaultEdge('cncf-go-note', 'cncf-go-1', 'replace platform path'),
    ],
    {
      audience: 'developers',
      useCase: 'Describe a GitOps platform with more substance than a cluster icon collage',
      launchPriority: 7,
      featured: true,
      difficulty: 'advanced',
      outcome: 'Lets platform teams start from a real GitOps operating model and trim it to their stack.',
      replacementHints: ['Platform portal', 'Packaging tool', 'Policy/identity controls', 'Runtime signals'],
      previewVariant: 'asset-rich',
    }
  ),
  createTemplate(
    'backend-api-request-handoff',
    'Backend API Request Handoff',
    'A sequence diagram for authenticated API requests, async handoff, persistence, and customer response.',
    'sequence',
    ['sequence', 'api', 'backend', 'handoff'],
    [
      {
        id: 'seq-client',
        type: NodeType.SEQUENCE_PARTICIPANT,
        position: { x: 0, y: 0 },
        data: { label: 'Web Client', seqParticipantKind: 'actor' },
      },
      {
        id: 'seq-edge',
        type: NodeType.SEQUENCE_PARTICIPANT,
        position: { x: 200, y: 0 },
        data: { label: 'API Gateway', seqParticipantKind: 'participant' },
      },
      {
        id: 'seq-api',
        type: NodeType.SEQUENCE_PARTICIPANT,
        position: { x: 400, y: 0 },
        data: { label: 'Orders API', seqParticipantKind: 'participant' },
      },
      {
        id: 'seq-worker',
        type: NodeType.SEQUENCE_PARTICIPANT,
        position: { x: 600, y: 0 },
        data: { label: 'Fulfillment Worker', seqParticipantKind: 'participant' },
      },
      {
        id: 'seq-db',
        type: NodeType.SEQUENCE_PARTICIPANT,
        position: { x: 800, y: 0 },
        data: { label: 'Postgres', seqParticipantKind: 'participant' },
      },
    ],
    [
      {
        id: 'seq-edge-1',
        source: 'seq-client',
        target: 'seq-edge',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'POST /orders',
        type: 'sequence_message',
        data: { seqMessageKind: 'sync', seqMessageOrder: 0 },
      },
      {
        id: 'seq-edge-2',
        source: 'seq-edge',
        target: 'seq-api',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'forward request + auth context',
        type: 'sequence_message',
        data: { seqMessageKind: 'sync', seqMessageOrder: 1 },
      },
      {
        id: 'seq-edge-3',
        source: 'seq-api',
        target: 'seq-db',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'create pending order',
        type: 'sequence_message',
        data: { seqMessageKind: 'sync', seqMessageOrder: 2 },
      },
      {
        id: 'seq-edge-4',
        source: 'seq-db',
        target: 'seq-api',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'order id',
        type: 'sequence_message',
        data: { seqMessageKind: 'return', seqMessageOrder: 3 },
      },
      {
        id: 'seq-edge-5',
        source: 'seq-api',
        target: 'seq-worker',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'enqueue fulfillment job',
        type: 'sequence_message',
        data: { seqMessageKind: 'async', seqMessageOrder: 4 },
      },
      {
        id: 'seq-edge-6',
        source: 'seq-worker',
        target: 'seq-db',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'mark order processing',
        type: 'sequence_message',
        data: { seqMessageKind: 'sync', seqMessageOrder: 5 },
      },
      {
        id: 'seq-edge-7',
        source: 'seq-db',
        target: 'seq-worker',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'state saved',
        type: 'sequence_message',
        data: { seqMessageKind: 'return', seqMessageOrder: 6 },
      },
      {
        id: 'seq-edge-8',
        source: 'seq-api',
        target: 'seq-edge',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: '202 Accepted + tracking id',
        type: 'sequence_message',
        data: { seqMessageKind: 'return', seqMessageOrder: 7 },
      },
      {
        id: 'seq-edge-9',
        source: 'seq-edge',
        target: 'seq-client',
        sourceHandle: 'top',
        targetHandle: 'top',
        label: 'response to caller',
        type: 'sequence_message',
        data: { seqMessageKind: 'return', seqMessageOrder: 8 },
      },
    ],
    {
      audience: 'developers',
      useCase: 'Explain backend request flow with concrete participants and message ordering',
      launchPriority: 9,
      featured: true,
      difficulty: 'starter',
      outcome: 'Gives engineers a sequence diagram they can directly adapt to a real API path.',
      replacementHints: ['Participant names', 'Endpoint', 'Async job step', 'Persistence calls'],
      previewVariant: 'sequence',
    }
  ),
  createTemplate(
    'product-discovery-workshop-map',
    'Product Discovery Workshop Map',
    'A discovery mindmap for goals, user pain, evidence, solution bets, and experiments.',
    'mindmap',
    ['mindmap', 'product', 'workshop', 'discovery'],
    [
      createMindmapNode('mm-root', 'Discovery Workshop', 0, 0, {
        mindmapDepth: 0,
        color: 'slate',
      }),
      createMindmapNode('mm-left-1', 'User Pain', -280, -200, {
        mindmapParentId: 'mm-root',
        mindmapSide: 'left',
        mindmapDepth: 1,
      }),
      createMindmapNode('mm-left-2', 'Evidence', -280, 40, {
        mindmapParentId: 'mm-root',
        mindmapSide: 'left',
        mindmapDepth: 1,
      }),
      createMindmapNode('mm-left-3', 'Constraints', -280, 280, {
        mindmapParentId: 'mm-root',
        mindmapSide: 'left',
        mindmapDepth: 1,
      }),
      createMindmapNode('mm-right-1', 'Solution Bets', 280, -200, {
        mindmapParentId: 'mm-root',
        mindmapSide: 'right',
        mindmapDepth: 1,
      }),
      createMindmapNode('mm-right-2', 'Experiments', 280, 40, {
        mindmapParentId: 'mm-root',
        mindmapSide: 'right',
        mindmapDepth: 1,
      }),
      createMindmapNode('mm-right-3', 'Success Signals', 280, 280, {
        mindmapParentId: 'mm-root',
        mindmapSide: 'right',
        mindmapDepth: 1,
      }),
      createMindmapNode('mm-leaf-1', 'Top complaint from interviews', -560, -280, {
        mindmapParentId: 'mm-left-1',
        mindmapSide: 'left',
        mindmapDepth: 2,
      }),
      createMindmapNode('mm-leaf-2', 'Activation drop-off metrics', -560, -40, {
        mindmapParentId: 'mm-left-2',
        mindmapSide: 'left',
        mindmapDepth: 2,
      }),
      createMindmapNode('mm-leaf-3', 'Engineering capacity this quarter', -560, 220, {
        mindmapParentId: 'mm-left-3',
        mindmapSide: 'left',
        mindmapDepth: 2,
      }),
      createMindmapNode('mm-leaf-4', 'Workflow assistant concept', 560, -280, {
        mindmapParentId: 'mm-right-1',
        mindmapSide: 'right',
        mindmapDepth: 2,
      }),
      createMindmapNode('mm-leaf-5', 'Prototype with five users', 560, -40, {
        mindmapParentId: 'mm-right-2',
        mindmapSide: 'right',
        mindmapDepth: 2,
      }),
      createMindmapNode('mm-leaf-6', 'Time to first value', 560, 220, {
        mindmapParentId: 'mm-right-3',
        mindmapSide: 'right',
        mindmapDepth: 2,
      }),
    ],
    [
      createDefaultEdge('mm-root', 'mm-left-1'),
      createDefaultEdge('mm-root', 'mm-left-2'),
      createDefaultEdge('mm-root', 'mm-left-3'),
      createDefaultEdge('mm-root', 'mm-right-1'),
      createDefaultEdge('mm-root', 'mm-right-2'),
      createDefaultEdge('mm-root', 'mm-right-3'),
      createDefaultEdge('mm-left-1', 'mm-leaf-1'),
      createDefaultEdge('mm-left-2', 'mm-leaf-2'),
      createDefaultEdge('mm-left-3', 'mm-leaf-3'),
      createDefaultEdge('mm-right-1', 'mm-leaf-4'),
      createDefaultEdge('mm-right-2', 'mm-leaf-5'),
      createDefaultEdge('mm-right-3', 'mm-leaf-6'),
    ],
    {
      audience: 'builders',
      useCase: 'Run a product discovery workshop with prompts that invite editing instead of blank branches',
      launchPriority: 7,
      featured: false,
      difficulty: 'starter',
      outcome: 'Turns the mindmap into a real workshop asset instead of a decorative brainstorming shell.',
      replacementHints: ['Workshop topic', 'Pain points', 'Evidence sources', 'Experiment ideas'],
    }
  ),
createTemplate(
    'aws-knowledge-base-pipeline',
    'AWS Knowledge Base Pipeline',
    'A complex architecture showing data sources, AWS processing, MCP integrations, and RAG UI flows.',
    'aws',
    ['aws', 'rag', 'architecture'],
    [
      createArchitectureNode('ds1', 'ZSmart KB File Dump', 'service', 'Database', 'blue', 972, 1865, ''),
      createArchitectureNode('ds2', 'U Mobile Website', 'service', 'Globe', 'blue', 2252, 1912, ''),
      createAssetNode('ds3', 'aws', 'Manual S3 Upload', 'Storage', 'storage-simple-storage-service', 1292, 1985),
      createArchitectureNode('ds4', 'Avows API', 'service', 'Plug', 'blue', 1932, 1998, ''),
      createArchitectureNode('ds5', 'GrowthOps API', 'service', 'Plug', 'blue', 1932, 1758, ''),
      createAssetNode('ig1', 'aws', 'S3 Raw Bucket', 'Storage', 'storage-simple-storage-service', 1612, 1878),
      createAssetNode('ig2', 'aws', 'AWS EventBridge', 'Application Integration', 'application-integration-eventbridge', 1932, 1878),
      createAssetNode('lm1', 'aws', 'Lambda: Dispatcher', 'Compute', 'compute-lambda', 2252, 1778),
      createAssetNode('lm2', 'aws', 'Lambda: Web Scraper', 'Compute', 'compute-lambda', 2572, 1898),
      createAssetNode('lm3', 'aws', 'Lambda: Doc Parser', 'Compute', 'compute-lambda', 2572, 1658),
      createAssetNode('lm4', 'aws', 'Lambda: CSV/Excel ETL', 'Compute', 'compute-lambda', 2572, 1778),
      createAssetNode('ix1', 'aws', 'AOSS: KBS Index', 'Analytics', 'analytics-opensearch-service', 3532, 1670),
      createAssetNode('ix2', 'aws', 'AOSS: Website Index', 'Analytics', 'analytics-opensearch-service', 3532, 1790),
      createAssetNode('ix3', 'aws', 'AOSS: Attachment Index', 'Analytics', 'analytics-opensearch-service', 3532, 2128),
      createAssetNode('ix4', 'aws', 'AOSS: SmartReply Index', 'Analytics', 'analytics-opensearch-service', 3532, 1430),
      createAssetNode('ix5', 'aws', 'AOSS: Cache Index', 'Analytics', 'analytics-opensearch-service', 3532, 744),
      createAssetNode('ah2', 'aws', 'AWS SageMaker STT', 'Artificial Intelligence', 'artificial-intelligence-sagemaker-ai', 972, 705),
      createAssetNode('ek1', 'aws', 'AWS EKS', 'Containers', 'containers-elastic-kubernetes-service', 1612, 453),
      createAssetNode('ek2', 'aws', 'Internal ALB', 'Networking Content Delivery', 'networking-content-delivery-elastic-load-balancing', 1292, 705),
      createAssetNode('ek3', 'aws', 'PrivateLink / VPC', 'Networking Content Delivery', 'networking-content-delivery-virtual-private-cloud', 5192, 352),
      createAssetNode('ek4', 'aws', 'AWS Secrets Manager', 'Security Identity Compliance', 'security-identity-compliance-secrets-manager', 1292, 530),
      createAssetNode('cr4', 'aws', 'DynamoDB: Job State', 'Databases', 'databases-dynamodb', 1932, 976),
      createAssetNode('cr5', 'aws', 'ElastiCache Redis', 'Databases', 'databases-elasticache', 1932, 736),
      createAssetNode('zs11', 'aws', 'AWS Location Service', 'Front End Web Mobile', 'front-end-web-mobile-location-service', 5192, 2204),
      createAssetNode('rg2', 'aws', 'AOSS KBS Vector Search', 'Analytics', 'analytics-opensearch-service', 3852, 1444),
      createAssetNode('rg3', 'aws', 'AOSS Attachment Search', 'Analytics', 'analytics-opensearch-service', 3852, 2115),
      createAssetNode('rg4', 'aws', 'AOSS Website Search', 'Analytics', 'analytics-opensearch-service', 3852, 1564),
      createAssetNode('nv1', 'aws', 'Amazon Nova Pro', 'Artificial Intelligence', 'artificial-intelligence-bedrock', 4172, 610),
      createArchitectureNode('pg2', 'PPID Flag Persist', 'service', 'Database', 'blue', 12, 12, ''),
      createArchitectureNode('ig3', 'SFTP Server', 'service', 'Server', 'blue', 1292, 1865, ''),
      createArchitectureNode('ch1', 'Text Chunker', 'service', 'Layers', 'blue', 2892, 1678, ''),
      createArchitectureNode('ch2', 'Cohere Embed Multilingual v3', 'service', 'Cpu', 'blue', 3212, 1678, ''),
      createArchitectureNode('ah1', 'AudioHook Integration', 'service', 'Mic', 'blue', 652, 705, ''),
      createArchitectureNode('ah3', 'Genesys Implicit Grant', 'service', 'Key', 'blue', 652, 585, ''),
      createArchitectureNode('ah4', 'Token Validator', 'service', 'UserCheck', 'blue', 972, 479, ''),
      createArchitectureNode('cr3', 'process_job_logic.py', 'service', 'GitBranch', 'blue', 2252, 744, ''),
      createArchitectureNode('sr1', 'Language Selector', 'service', 'Search', 'blue', 2572, 730, ''),
      createArchitectureNode('sr2', 'Prospect Detection', 'service', 'UserCheck', 'blue', 2572, 850, ''),
      createArchitectureNode('sr4', 'CacheManager.get()', 'service', 'Search', 'blue', 3212, 744, ''),
      createArchitectureNode('tf1', 'get_filtered_tools()', 'service', 'Filter', 'blue', 3532, 504, ''),
      createArchitectureNode('tf2', 'Orchestrator Prompt', 'service', 'FileText', 'blue', 3852, 490, ''),
      createArchitectureNode('tf3', 'Responder Prompt', 'service', 'FileText', 'blue', 3852, 610, ''),
      createArchitectureNode('tf4', 'Previous Reply Context', 'service', 'FileText', 'blue', 3532, 624, ''),
      createArchitectureNode('oc3', 'Malformed XML Guard', 'service', 'Shield', 'blue', 4822, 1930, ''),
      createArchitectureNode('rg5', 'Cohere Rerank v3', 'service', 'Filter', 'blue', 4172, 1464, ''),
      createArchitectureNode('nv2', 'Anti-Repetition Check', 'service', 'AlertCircle', 'blue', 272, 12, ''),
      createArchitectureNode('nv3', 'XML Artifact Cleanup', 'service', 'RefreshCw', 'blue', 532, 12, ''),
      createArchitectureNode('nv4', 'Language Enforcement', 'service', 'Search', 'blue', 792, 12, ''),
      createArchitectureNode('pg1', 'rapidfuzz Similarity', 'service', 'LineChart', 'blue', 1052, 12, ''),
      createArchitectureNode('pg3', 'CacheManager.insert()', 'service', 'Database', 'blue', 1312, 12, ''),
      createArchitectureNode('pg4', 'Sources Attribution', 'service', 'FileText', 'blue', 1572, 12, ''),
      createArchitectureNode('lc1', 'Customer Phone Call', 'service', 'Phone', 'blue', 12, 599, ''),
      createArchitectureNode('lc3', 'Genesys Desktop KB', 'service', 'Eye', 'blue', 652, 465, ''),
      createArchitectureNode('lc4', 'Agent (Smart Assist)', 'service', 'User', 'blue', 1292, 429, ''),
      createArchitectureNode('sr5', 'Cache HIT → Return', 'service', 'Zap', 'blue', 3532, 864, ''),
      createArchitectureNode('op1', 'Smart Reply Panel', 'service', 'MessageSquare', 'blue', 3852, 864, ''),
      createArchitectureNode('op2', 'Smart Assist Panel', 'service', 'Bot', 'blue', 1832, 12, ''),
      createArchitectureNode('op3', 'Sentiment Gauge', 'service', 'LineChart', 'blue', 2092, 12, ''),
      createArchitectureNode('op4', 'Feedback Thumbs-Down', 'service', 'ThumbsDown', 'blue', 2352, 12, ''),
      createAssetNode('op5', 'aws', 'DynamoDB: Audit Trail', 'Databases', 'databases-dynamodb', 2612, 12),
      createArchitectureNode('lc2', 'Genesys Cloud CX', 'service', 'Network', 'blue', 332, 599, ''),
      createArchitectureNode('cr1', 'ZSmartClient CRM Model', 'service', 'Database', 'blue', 1932, 453, ''),
      createArchitectureNode('cr2', 'CMS API', 'service', 'Plug', 'blue', 1932, 856, ''),
      createArchitectureNode('tl1', 'search_knowledge_base', 'service', 'Search', 'blue', 4822, 2050, ''),
      createArchitectureNode('tl2', 'ppid_verification', 'service', 'UserCheck', 'blue', 4822, 970, ''),
      createArchitectureNode('tl3', 'no_network_troubleshoot', 'service', 'Wrench', 'blue', 4822, 2170, ''),
      createArchitectureNode('tl4', 'slow_internet_troubleshoot', 'service', 'Wrench', 'blue', 4822, 2290, ''),
      createArchitectureNode('tl5', 'find_nearest_stores', 'service', 'Globe', 'blue', 4822, 2410, ''),
      createArchitectureNode('tl6', 'get_country_services', 'service', 'Globe', 'blue', 4822, 490, ''),
      createArchitectureNode('tl7', 'Smartphone_Details', 'service', 'Smartphone', 'blue', 4822, 730, ''),
      createArchitectureNode('tl8', 'Device_Stock_Availability', 'service', 'Package', 'blue', 4822, 1570, ''),
      createArchitectureNode('tl9', 'customer_eligible_offers', 'service', 'Star', 'blue', 4822, 610, ''),
      createArchitectureNode('tl10', 'bills_and_payments', 'service', 'Wrench', 'blue', 4822, 850, ''),
      createArchitectureNode('tl11', 'query_mnp_order', 'service', 'Repeat', 'blue', 4822, 1090, ''),
      createArchitectureNode('tl12', 'get_contract_details', 'service', 'FileText', 'blue', 4822, 1210, ''),
      createArchitectureNode('tl13', 'post2pre_downgrade', 'service', 'ArrowDown', 'blue', 4822, 1330, ''),
      createArchitectureNode('tl14', 'post2post_downgrade', 'service', 'ArrowDown', 'blue', 4822, 1450, ''),
      createArchitectureNode('tl15', 'pre2post_upgrade', 'service', 'ArrowUp', 'blue', 4822, 1690, ''),
      createArchitectureNode('tl16', 'post2post_upgrade', 'service', 'ArrowUp', 'blue', 4822, 1810, ''),
      createArchitectureNode('zs1', 'ZSmart API Gateway', 'service', 'Network', 'blue', 5192, 472, ''),
      createArchitectureNode('zs2', 'qryCustomerDetail', 'service', 'Database', 'blue', 5512, 112, ''),
      createArchitectureNode('zs3', 'checkCustomerEligibility', 'service', 'Database', 'blue', 5512, 352, ''),
      createArchitectureNode('zs4', 'checkChangeSubsPlan', 'service', 'Database', 'blue', 5512, 712, ''),
      createArchitectureNode('zs5', 'queryBill', 'service', 'Database', 'blue', 5512, 472, ''),
      createArchitectureNode('zs6', 'queryFFGroupInfo', 'service', 'Database', 'blue', 5512, 592, ''),
      createArchitectureNode('zs7', 'getSubscriberBaseInfo', 'service', 'Database', 'blue', 5512, 832, ''),
      createArchitectureNode('zs8', 'querySubscriberAgreement', 'service', 'Database', 'blue', 5512, 232, ''),
      createArchitectureNode('zs9', 'queryMNPOrder', 'service', 'Database', 'blue', 2872, 12, ''),
      createArchitectureNode('zs10', 'SQVE / SIM Vulnerability', 'service', 'Network', 'blue', 5512, 2204, ''),
      createArchitectureNode('sr3', 'smartReply() entry', 'service', 'Zap', 'blue', 2892, 744, ''),
      createArchitectureNode('oc2', 'Tool Loop', 'service', 'RefreshCw', 'blue', 4492, 1450, ''),
      createArchitectureNode('oc1', 'Claude Haiku 4.5', 'service', 'Brain', 'blue', 4172, 490, ''),
      createArchitectureNode('rg1', 'Retriever.get_context()', 'service', 'Search', 'blue', 3532, 1550, ''),
    ],
    [
      createDefaultEdge('ds1', 'ig3'),
      createDefaultEdge('ds2', 'lm2'),
      createDefaultEdge('ds3', 'ig1'),
      createDefaultEdge('ds4', 'lm1'),
      createDefaultEdge('ds5', 'lm1'),
      createDefaultEdge('ig3', 'ig1'),
      createDefaultEdge('ig1', 'ig2'),
      createDefaultEdge('ig2', 'lm1'),
      createDefaultEdge('lm1', 'lm2'),
      createDefaultEdge('lm1', 'lm3'),
      createDefaultEdge('lm1', 'lm4'),
      createDefaultEdge('lm2', 'ch1'),
      createDefaultEdge('lm3', 'ch1'),
      createDefaultEdge('lm4', 'ch1'),
      createDefaultEdge('ch1', 'ch2'),
      createDefaultEdge('ch2', 'ix1'),
      createDefaultEdge('ch2', 'ix2'),
      createDefaultEdge('ch2', 'ix3'),
      createDefaultEdge('ch2', 'ix4'),
      createDefaultEdge('lc1', 'lc2'),
      createDefaultEdge('lc2', 'ah1'),
      createDefaultEdge('ah1', 'ah2'),
      createDefaultEdge('ah2', 'ek2'),
      createDefaultEdge('lc2', 'ah3'),
      createDefaultEdge('ah3', 'ah4'),
      createDefaultEdge('ah4', 'ek1'),
      createDefaultEdge('ek2', 'ek1'),
      createDefaultEdge('ek4', 'ek1'),
      createDefaultEdge('ek3', 'ek1'),
      createDefaultEdge('lc3', 'ah4'),
      createDefaultEdge('lc4', 'ek1'),
      createDefaultEdge('ek1', 'cr1'),
      createDefaultEdge('cr1', 'zs1'),
      createDefaultEdge('zs1', 'zs2'),
      createDefaultEdge('cr1', 'cr3'),
      createDefaultEdge('ek1', 'cr2'),
      createDefaultEdge('cr2', 'cr3'),
      createDefaultEdge('cr4', 'cr3'),
      createDefaultEdge('cr5', 'cr3'),
      createDefaultEdge('cr3', 'sr1'),
      createDefaultEdge('cr3', 'sr2'),
      createDefaultEdge('sr1', 'sr3'),
      createDefaultEdge('sr2', 'sr3'),
      createDefaultEdge('sr3', 'sr4'),
      createDefaultEdge('sr4', 'ix5'),
      createDefaultEdge('sr4', 'sr5'),
      createDefaultEdge('sr5', 'op1'),
      createDefaultEdge('sr4', 'tf1'),
      createDefaultEdge('tf1', 'tf2'),
      createDefaultEdge('tf1', 'tf3'),
      createDefaultEdge('tf4', 'tf3'),
      createDefaultEdge('tf2', 'oc1'),
      createDefaultEdge('tf3', 'nv1'),
      createDefaultEdge('oc1', 'oc2'),
      createDefaultEdge('oc2', 'oc3'),
      createDefaultEdge('oc2', 'tl1'),
      createDefaultEdge('oc2', 'tl2'),
      createDefaultEdge('oc2', 'tl3'),
      createDefaultEdge('oc2', 'tl4'),
      createDefaultEdge('oc2', 'tl5'),
      createDefaultEdge('oc2', 'tl6'),
      createDefaultEdge('oc2', 'tl7'),
      createDefaultEdge('oc2', 'tl8'),
      createDefaultEdge('oc2', 'tl9'),
      createDefaultEdge('oc2', 'tl10'),
      createDefaultEdge('oc2', 'tl11'),
      createDefaultEdge('oc2', 'tl12'),
      createDefaultEdge('oc2', 'tl13'),
      createDefaultEdge('oc2', 'tl14'),
      createDefaultEdge('oc2', 'tl15'),
      createDefaultEdge('oc2', 'tl16'),
      createDefaultEdge('tl1', 'rg1'),
      createDefaultEdge('rg1', 'rg2'),
      createDefaultEdge('rg1', 'rg3'),
      createDefaultEdge('rg1', 'rg4'),
      createDefaultEdge('ix1', 'rg2'),
      createDefaultEdge('ix3', 'rg3'),
      createDefaultEdge('ix2', 'rg4'),
      createDefaultEdge('rg2', 'rg5'),
      createDefaultEdge('rg3', 'rg5'),
      createDefaultEdge('rg4', 'rg5'),
      createDefaultEdge('rg5', 'oc2'),
      createDefaultEdge('tl2', 'rg1'),
      createDefaultEdge('tl3', 'zs11'),
      createDefaultEdge('tl4', 'zs11'),
      createDefaultEdge('zs11', 'zs10'),
      createDefaultEdge('tl3', 'zs1'),
      createDefaultEdge('tl4', 'zs1'),
      createDefaultEdge('tl5', 'zs11'),
      createDefaultEdge('tl6', 'ek3'),
      createDefaultEdge('tl10', 'zs1'),
      createDefaultEdge('tl11', 'zs1'),
      createDefaultEdge('tl12', 'zs1'),
      createDefaultEdge('tl13', 'zs1'),
      createDefaultEdge('tl14', 'zs1'),
      createDefaultEdge('tl15', 'zs1'),
      createDefaultEdge('tl16', 'zs1'),
      createDefaultEdge('zs1', 'zs3'),
      createDefaultEdge('zs1', 'zs4'),
      createDefaultEdge('zs1', 'zs5'),
      createDefaultEdge('zs1', 'zs6'),
      createDefaultEdge('zs1', 'zs7'),
      createDefaultEdge('zs1', 'zs8'),
    ],
    {
      audience: 'builders',
      useCase: 'Deploying a complex RAG-based AI pipeline on AWS',
      launchPriority: 5,
      featured: true,
      difficulty: 'advanced',
      outcome: 'A complete view of data ingestion, processing, and agentic integrations',
      replacementHints: ['AWS regions', 'OpenSearch domains', 'Lambda function names'],
    }
  ),

  createTemplate(
    'pca-system-pipeline',
    'PCA System — End-to-End Pipeline',
    'Complete architecture showing Genesys ingestion, Lambda chain, SQS, EKS/FastAPI scoring service, Bedrock KPI evaluation (CR1/CR2), DynamoDB storage, and retry/reporting flows for U Mobile AICC Post-Call Analytics.',
    'aws',
    ['aws', 'pca', 'architecture', 'bedrock', 'genesys'],
    [
      // ── STAGE 0: TELEPHONY / SOURCE ──────────────────────────────────────
      createArchitectureNode('src1', 'Customer Phone Call', 'service', 'Phone', 'blue', 12, 648, ''),
      createArchitectureNode('src2', 'Genesys Cloud CX (mypurecloud.jp)', 'service', 'Network', 'blue', 332, 542, ''),
      createArchitectureNode('src3', 'Genesys OAuth Client Credentials', 'service', 'Key', 'blue', 12, 528, ''),
      createArchitectureNode('src4', 'Call Recording (.opus)', 'service', 'Mic', 'blue', 652, 542, ''),

      // ── STAGE 1: GENESYS_FUNC LAMBDA (1st Lambda) ────────────────────────
      createAssetNode('gf1', 'aws', 'Lambda: Genesys_func (1st)', 'Compute', 'compute-lambda', 972, 542),
      createArchitectureNode('gf2', 'ConversationService.fetch_conversations()', 'service', 'Search', 'blue', 1292, 528, ''),
      createArchitectureNode('gf3', 'get_conversation_recordings_metadata()', 'service', 'FileText', 'blue', 1612, 528, ''),
      createArchitectureNode('gf4', 'CSC Filtering + Random Sampling Logic', 'service', 'Filter', 'blue', 1932, 422, ''),
      createArchitectureNode('gf5', 'Agent Tenure + CSAT/DSAT Checks', 'service', 'UserCheck', 'blue', 2252, 635, ''),
      createAssetNode('gf6', 'aws', 'DynamoDB: pcaRecordLevelTracker (seed Pending)', 'Databases', 'databases-dynamodb', 2252, 408),

      // ── STAGE 2: S3_FUNC LAMBDA (2nd Lambda) ─────────────────────────────
      createAssetNode('sf1', 'aws', 'Lambda: S3_func (2nd)', 'Compute', 'compute-lambda', 1292, 768),
      createArchitectureNode('sf2', 'download_file() — fetch .opus via aiohttp', 'service', 'ArrowDown', 'blue', 1612, 768, ''),
      createArchitectureNode('sf3', 'run_ffmpeg() — opus → wav (PCM 16-bit, 8kHz)', 'service', 'RefreshCw', 'blue', 1932, 768, ''),
      createArchitectureNode('sf4', 'build_s3_metadata() — flatten + filter keys', 'service', 'FileText', 'blue', 2252, 755, ''),
      createAssetNode('sf5', 'aws', 'S3: umobile-genesys-audio-recordings', 'Storage', 'storage-simple-storage-service', 5132, 788),
      createAssetNode('sf6', 'aws', 'S3: umobile-genesys-pca', 'Storage', 'storage-simple-storage-service', 5772, 642),

      // ── STAGE 3: SQS QUEUE ────────────────────────────────────────────────
      createAssetNode('sqs1', 'aws', 'SQS: pca-kpi-queue', 'Application Integration', 'application-integration-simple-queue-service', 2572, 742),

      // ── STAGE 4: PCA-KPI-PROCESSOR LAMBDA (3rd Lambda) ───────────────────
      createAssetNode('kp1', 'aws', 'Lambda: pca-kpi-processor (3rd)', 'Compute', 'compute-lambda', 2892, 742),
      createArchitectureNode('kp2', 'Fire-and-Forget POST (timeout=1s)', 'service', 'Zap', 'blue', 3212, 742, ''),

      // ── STAGE 5: RETRY LAMBDA ─────────────────────────────────────────────
      createAssetNode('rt1', 'aws', 'Lambda: pca-retry-call-processing', 'Compute', 'compute-lambda', 2572, 408),
      createArchitectureNode('rt2', 'Query batchId WHERE status=Pending', 'service', 'Search', 'blue', 2892, 408, ''),
      createArchitectureNode('rt3', 'Re-POST to API (non-idempotent: status never set after dispatch)', 'service', 'AlertCircle', 'red', 3212, 408, ''),

      // ── STAGE 6: EKS / FASTAPI ENTRY ──────────────────────────────────────
      createAssetNode('ek1', 'aws', 'EKS Cluster (FastAPI)', 'Containers', 'containers-elastic-kubernetes-service', 3852, 422),
      createAssetNode('ek2', 'aws', 'Internal ALB', 'Networking Content Delivery', 'networking-content-delivery-elastic-load-balancing', 3532, 422),
      createArchitectureNode('ap1', 'POST /api/analyze-call [app.py]', 'service', 'Plug', 'blue', 4172, 422, ''),
      createArchitectureNode('ap2', 'asyncio.Semaphore(10) — concurrency gate', 'service', 'Lock', 'blue', 4492, 422, ''),

      // ── STAGE 7: METADATA + AUDIO PREP [utils.py / audio_processor.py] ───
      createArchitectureNode('mp1', 'analyze_call_metadata() [utils.py]', 'service', 'FileText', 'blue', 4812, 408, ''),
      createArchitectureNode('mp2', 'Hold/Closing/Day/CallingNumber calc', 'service', 'LineChart', 'blue', 5132, 408, ''),
      createArchitectureNode('mp3', 'get_audio_from_s3() — aioboto3 async fetch', 'service', 'ArrowDown', 'blue', 4812, 542, ''),
      createArchitectureNode('mp4', 'audio_processor.process_audio()', 'service', 'Mic', 'blue', 5132, 528, ''),
      createAssetNode('mp5', 'aws', 'SageMaker Endpoint: umobile-stt-model (Whisper)', 'Artificial Intelligence', 'artificial-intelligence-sagemaker-ai', 5452, 748),
      createArchitectureNode('mp6', 'upload_transcription_to_s3()', 'service', 'ArrowUp', 'blue', 5452, 628, ''),
      createArchitectureNode('mp7', 'os.remove(temp_audio_path) — cleanup (finally)', 'service', 'Trash2', 'blue', 5452, 508, ''),

      // ── STAGE 8: ANALYZER ENTRY [kpi_extractor.py] ───────────────────────
      createArchitectureNode('an1', 'BedrockTranscriptAnalyzer.analyze_transcript()', 'service', 'Brain', 'blue', 5772, 508, ''),
      createArchitectureNode('an2', 'Build transcript slices (opening/closing/summary)', 'service', 'FileText', 'blue', 9932, 522, ''),
      createArchitectureNode('an3', 'disconnectType mapping (peer/client/endpoint)', 'service', 'GitBranch', 'blue', 10252, 508, ''),
      createArchitectureNode('an4', 'KB Query Extractor + TF-IDF Cosine Similarity', 'service', 'Search', 'blue', 10252, 1722, ''),
      createArchitectureNode('an5', 'kb.txt / sop.json (local KB enrichment)', 'service', 'Database', 'blue', 10572, 1769, ''),

      // ── STAGE 9: CSC DATA FETCH + MSISDN RESOLUTION ──────────────────────
      createAssetNode('csc1', 'aws', 'DynamoDB: pcaCSCDataFiltered', 'Databases', 'databases-dynamodb', 6092, 125),
      createArchitectureNode('csc2', 'Impacted MSISDN Resolution (4-level fallback)', 'service', 'GitBranch', 'blue', 6412, 125, ''),
      createArchitectureNode('csc3', 'Branch A: case_data_list present → direct match', 'service', 'CheckCircle', 'blue', 8652, 125, ''),
      createArchitectureNode('csc4', 'Branch B: empty → Verbal Number B Extraction', 'service', 'AlertCircle', 'amber', 6732, 186, ''),

      // ── STAGE 9b: VERBAL NUMBER B [verbal_number_extractor.py] ───────────
      createArchitectureNode('vb1', 'VerbalNumberExtractor.extract()', 'service', 'Search', 'blue', 7052, 186, ''),
      createArchitectureNode('vb2', '_build_early_transcript_text() — first 50% turns', 'service', 'FileText', 'blue', 7372, 186, ''),
      createArchitectureNode('vb3', 'Bedrock call (max_tokens=200, retry x3)', 'service', 'Brain', 'blue', 7692, 186, ''),
      createArchitectureNode('vb4', 'Suffix-strip search loop (5 attempts)', 'service', 'RefreshCw', 'blue', 8012, 173, ''),
      createAssetNode('vb5', 'aws', 'DynamoDB: pcaCSCdata', 'Databases', 'databases-dynamodb', 8332, 173),

      // ── STAGE 10: CR2 — LCA STATE + BILLING [utils.py] ───────────────────
      createAssetNode('lca1', 'aws', 'DynamoDB: conversation_results (l2 records)', 'Databases', 'databases-dynamodb', 8972, 180),
      createArchitectureNode('lca2', 'fetch_lca_state() — is_lca_enabled check', 'service', 'Search', 'blue', 9292, 180, ''),
      createArchitectureNode('lca3', 'CR1: LCA MSISDN Override (lca_msisdn != calling)', 'service', 'AlertCircle', 'amber', 9612, 286, ''),
      createArchitectureNode('lca4', 'extract_billing() — 3 API prefix check', 'service', 'Filter', 'blue', 9612, 166, ''),
      createArchitectureNode('lca5', 'cents_to_rm() — 5 billing fields extracted', 'service', 'FileText', 'blue', 9932, 166, ''),
      createArchitectureNode('lca6', 'build_lca_reference() — format for prompt', 'service', 'FileText', 'blue', 10572, 166, ''),

      // ── STAGE 11: IVR SCENARIO DETECTION ──────────────────────────────────
      createArchitectureNode('ivr1', 'IVR Scenario Detection (impacted != calling)', 'service', 'GitBranch', 'blue', 9932, 300, ''),
      createArchitectureNode('ivr2', 'case_logging prompt prep (ivr_number injection)', 'service', 'FileText', 'blue', 10252, 300, ''),

      // ── STAGE 12: PARALLEL KPI TASKS [kpi_extractor.py + prompts.py] ─────
      createArchitectureNode('kpi0', 'opening (first 25%)', 'service', 'FileText', 'blue', 10922, 568, ''),
      createArchitectureNode('kpi1', 'communication_skills', 'service', 'FileText', 'blue', 10922, 688, ''),
      createArchitectureNode('kpi2', 'professionalism', 'service', 'FileText', 'blue', 10922, 808, ''),
      createArchitectureNode('kpi3', 'information_provided (KB-enriched)', 'service', 'FileText', 'blue', 10922, 928, ''),
      createArchitectureNode('kpi4', 'internal_policies (SOP-enriched)', 'service', 'FileText', 'blue', 10922, 1048, ''),
      createArchitectureNode('kpi5', 'compliance_adherence', 'service', 'FileText', 'blue', 10922, 1168, ''),
      createArchitectureNode('kpi6', 'call_summary (max_tokens=3000)', 'service', 'FileText', 'blue', 10922, 1288, ''),
      createArchitectureNode('kpi7', 'case_logging (calling/impacted/ivr injected)', 'service', 'FileText', 'blue', 10922, 1408, ''),
      createArchitectureNode('kpi8', 'closing (conditional: closing != None)', 'service', 'FileText', 'blue', 10922, 1528, ''),
      createArchitectureNode('kpi9', 'holding (conditional: hold present)', 'service', 'FileText', 'blue', 10922, 1648, ''),
      createArchitectureNode('kpi10', 'CR2: execution (conditional: billing != None)', 'service', 'AlertCircle', 'amber', 10922, 448, ''),
      createArchitectureNode('kpi_gather', 'asyncio.gather() — ThreadPoolExecutor(25)', 'service', 'Layers', 'blue', 10572, 495, ''),

      // ── STAGE 13: BEDROCK MODELS [bedrock_client.py] ─────────────────────
      createArchitectureNode('br1', 'BedrockClient.generate_response()', 'service', 'Brain', 'blue', 11242, 1048, ''),
      createAssetNode('br2', 'aws', 'Bedrock: Claude Sonnet 4.6 (APAC cross-region)', 'Artificial Intelligence', 'artificial-intelligence-bedrock', 11882, 1155),
      createAssetNode('br3', 'aws', 'Bedrock: Amazon Nova Pro (inference profile)', 'Artificial Intelligence', 'artificial-intelligence-bedrock', 11882, 1035),
      createArchitectureNode('br4', 'Model ID routing ("nova-pro" in model_id)', 'service', 'GitBranch', 'blue', 11562, 1048, ''),
      createArchitectureNode('br5', 'JSON parse + retry loop (3 attempts)', 'service', 'RefreshCw', 'blue', 12202, 1048, ''),

      // ── STAGE 14: POST-PROCESSING [kpi_extractor.py] ─────────────────────
      createArchitectureNode('pp1', 'Stage 9: CR2 Execution KPI post-processing', 'service', 'FileText', 'blue', 12522, 1031, ''),
      createArchitectureNode('pp2', 'Stage 10: Hold KPI + DeadAirDetector.analyze()', 'service', 'FileText', 'blue', 12522, 1151, ''),
      createArchitectureNode('pp3', 'Stage 11: Closing — 3-second wait rule check', 'service', 'FileText', 'blue', 12522, 1271, ''),
      createArchitectureNode('pp4', 'Stage 12: PDPA → Business Policy (key normalize)', 'service', 'FileText', 'blue', 12522, 1391, ''),
      createArchitectureNode('pp5', 'Stage 13: Sentiment + Customer Issue (Nova Pro)', 'service', 'LineChart', 'blue', 12522, 1511, ''),
      createArchitectureNode('pp6', 'Stage 14: find_duplicates() — redundant case logs', 'service', 'RefreshCw', 'blue', 12522, 119, ''),

      // ── STAGE 15: CRITICAL REPORT GENERATION [main.py] ───────────────────
      createArchitectureNode('rep1', 'generate_critical_report() [main.py]', 'service', 'FileText', 'blue', 12842, 1157, ''),
      createArchitectureNode('rep2', 'PHASE_1_ONLY filter (exclude policy categories)', 'service', 'Filter', 'blue', 13162, 1157, ''),
      createArchitectureNode('rep3', 'calculate_overall_status() per KPI dict', 'service', 'LineChart', 'blue', 13482, 1157, ''),
      createArchitectureNode('rep4', 'Non Critical / Customer / Business / Compliance scoring', 'service', 'LineChart', 'blue', 13802, 1157, ''),
      createArchitectureNode('rep5', 'overall_critical_score (100%/0%)', 'service', 'CheckCircle', 'blue', 14122, 1157, ''),

      // ── STAGE 16: FINAL STORAGE + TRACKERS ────────────────────────────────
      createAssetNode('db1', 'aws', 'DynamoDB: pcaCallAnalysisResults', 'Databases', 'databases-dynamodb', 14442, 1257),
      createAssetNode('db2', 'aws', 'DynamoDB: postCallAnalysis_CallList', 'Databases', 'databases-dynamodb', 14442, 1137),
      createAssetNode('db3', 'aws', 'DynamoDB: pcaRecordLevelTracker (SET Completed)', 'Databases', 'databases-dynamodb', 14442, 1390),
      createAssetNode('db4', 'aws', 'DynamoDB: pcaBatchLevelTracker (ADD completed/in_progress)', 'Databases', 'databases-dynamodb', 14762, 1390),
      createArchitectureNode('db5', 'batch_id timezone mismatch (UTC vs UTC+8) — known bug', 'service', 'AlertCircle', 'red', 15082, 1390, ''),

      // ── SUPPORTING LAMBDAS (CSC / CSAT / BDA CONFIG) ──────────────────────
      createAssetNode('sup1', 'aws', 'Lambda: CIC-CASE-data', 'Compute', 'compute-lambda', 5772, 112),
      createAssetNode('sup2', 'aws', 'Lambda: CIC_CSAT_data', 'Compute', 'compute-lambda', 1612, 648),
      createAssetNode('sup3', 'aws', 'Lambda: PCA-BDA-CONFIG', 'Compute', 'compute-lambda', 1292, 408),
      createAssetNode('sqs2', 'aws', 'SQS FIFO: CSC_CREATED_SYNC_UAT_GENAI', 'Application Integration', 'application-integration-simple-queue-service', 5452, 112),
      createAssetNode('sqs3', 'aws', 'SQS FIFO: CSC_CSAT_SYNC_GENAI', 'Application Integration', 'application-integration-simple-queue-service', 1292, 648),
      createAssetNode('csat1', 'aws', 'DynamoDB: pcaCSATdata', 'Databases', 'databases-dynamodb', 1932, 648),
      createAssetNode('bda1', 'aws', 'DynamoDB: pcaBDAconfigurations', 'Databases', 'databases-dynamodb', 1612, 408),

      // ── STANDALONE SETTINGS TABLES (not linked to call pipeline) ─────────
      createAssetNode('set1', 'aws', 'DynamoDB: pcaCallAnalyticsSettings (standalone)', 'Databases', 'databases-dynamodb', 12, 12),
      createAssetNode('set2', 'aws', 'DynamoDB: pcaCallConfigurationsSettings (standalone)', 'Databases', 'databases-dynamodb', 272, 12),

      // ── REPORTING / UI ────────────────────────────────────────────────────
      createArchitectureNode('ui1', 'Excel/CSV Report Generator', 'service', 'FileText', 'blue', 14762, 1150, ''),
      createArchitectureNode('ui2', 'Frontend UI Dashboard', 'service', 'Globe', 'blue', 15082, 1150, ''),
      createArchitectureNode('ui3', 'Client Signoff Doc (Logical Data Model)', 'service', 'FileText', 'blue', 14762, 1270, ''),
    ],
    [
      // Telephony / ingest
      createDefaultEdge('src1', 'src2'),
      createDefaultEdge('src3', 'src2'),
      createDefaultEdge('src2', 'src4'),
      createDefaultEdge('src4', 'gf1'),

      // Genesys_func (1st Lambda)
      createDefaultEdge('gf1', 'gf2'),
      createDefaultEdge('gf2', 'gf3'),
      createDefaultEdge('gf3', 'gf4'),
      createDefaultEdge('gf4', 'gf5'),
      createDefaultEdge('gf4', 'gf6'),
      createDefaultEdge('gf1', 'sf1'),

      // S3_func (2nd Lambda)
      createDefaultEdge('sf1', 'sf2'),
      createDefaultEdge('sf2', 'sf3'),
      createDefaultEdge('sf3', 'sf4'),
      createDefaultEdge('sf4', 'sf5'),
      createDefaultEdge('sf3', 'sf6'),
      createDefaultEdge('sf4', 'sqs1'),

      // SQS → pca-kpi-processor (3rd Lambda)
      createDefaultEdge('sqs1', 'kp1'),
      createDefaultEdge('kp1', 'kp2'),
      createDefaultEdge('kp2', 'ek2'),

      // Retry lambda path
      createDefaultEdge('gf6', 'rt1'),
      createDefaultEdge('rt1', 'rt2'),
      createDefaultEdge('rt2', 'rt3'),
      createDefaultEdge('rt3', 'ek2'),

      // EKS / FastAPI entry
      createDefaultEdge('ek2', 'ek1'),
      createDefaultEdge('ek1', 'ap1'),
      createDefaultEdge('ap1', 'ap2'),

      // Metadata + audio prep
      createDefaultEdge('ap2', 'mp1'),
      createDefaultEdge('mp1', 'mp2'),
      createDefaultEdge('ap2', 'mp3'),
      createDefaultEdge('mp3', 'sf5'),
      createDefaultEdge('mp3', 'mp4'),
      createDefaultEdge('mp4', 'mp5'),
      createDefaultEdge('mp4', 'mp6'),
      createDefaultEdge('mp6', 'sf6'),
      createDefaultEdge('mp4', 'mp7'),

      // Analyzer entry
      createDefaultEdge('mp7', 'an1'),
      createDefaultEdge('an1', 'an2'),
      createDefaultEdge('an2', 'an3'),
      createDefaultEdge('an2', 'an4'),
      createDefaultEdge('an4', 'an5'),
      createDefaultEdge('an4', 'br1'),

      // CSC fetch + MSISDN resolution
      createDefaultEdge('an1', 'csc1'),
      createDefaultEdge('csc1', 'csc2'),
      createDefaultEdge('csc2', 'csc3'),
      createDefaultEdge('csc2', 'csc4'),

      // Verbal Number B path
      createDefaultEdge('csc4', 'vb1'),
      createDefaultEdge('vb1', 'vb2'),
      createDefaultEdge('vb2', 'vb3'),
      createDefaultEdge('vb3', 'br1'),
      createDefaultEdge('vb3', 'vb4'),
      createDefaultEdge('vb4', 'vb5'),
      createDefaultEdge('vb5', 'csc3'),

      // CR2 LCA + billing
      createDefaultEdge('csc3', 'lca1'),
      createDefaultEdge('lca1', 'lca2'),
      createDefaultEdge('lca2', 'lca3'),
      createDefaultEdge('lca2', 'lca4'),
      createDefaultEdge('lca4', 'lca5'),
      createDefaultEdge('lca5', 'lca6'),

      // IVR scenario detection
      createDefaultEdge('lca3', 'ivr1'),
      createDefaultEdge('csc3', 'ivr1'),
      createDefaultEdge('ivr1', 'ivr2'),

      // Parallel KPI task fan-out
      createDefaultEdge('ivr2', 'kpi_gather'),
      createDefaultEdge('an3', 'kpi_gather'),
      createDefaultEdge('kpi_gather', 'kpi0'),
      createDefaultEdge('kpi_gather', 'kpi1'),
      createDefaultEdge('kpi_gather', 'kpi2'),
      createDefaultEdge('kpi_gather', 'kpi3'),
      createDefaultEdge('kpi_gather', 'kpi4'),
      createDefaultEdge('kpi_gather', 'kpi5'),
      createDefaultEdge('kpi_gather', 'kpi6'),
      createDefaultEdge('kpi_gather', 'kpi7'),
      createDefaultEdge('kpi_gather', 'kpi8'),
      createDefaultEdge('kpi_gather', 'kpi9'),
      createDefaultEdge('lca6', 'kpi10'),
      createDefaultEdge('kpi_gather', 'kpi10'),

      // All KPI tasks call Bedrock
      createDefaultEdge('kpi0', 'br1'),
      createDefaultEdge('kpi1', 'br1'),
      createDefaultEdge('kpi2', 'br1'),
      createDefaultEdge('kpi3', 'br1'),
      createDefaultEdge('kpi4', 'br1'),
      createDefaultEdge('kpi5', 'br1'),
      createDefaultEdge('kpi6', 'br1'),
      createDefaultEdge('kpi7', 'br1'),
      createDefaultEdge('kpi8', 'br1'),
      createDefaultEdge('kpi9', 'br1'),
      createDefaultEdge('kpi10', 'br1'),

      // Bedrock routing
      createDefaultEdge('br1', 'br4'),
      createDefaultEdge('br4', 'br2'),
      createDefaultEdge('br4', 'br3'),
      createDefaultEdge('br2', 'br5'),
      createDefaultEdge('br3', 'br5'),

      // Post-processing stages
      createDefaultEdge('br5', 'pp1'),
      createDefaultEdge('br5', 'pp2'),
      createDefaultEdge('br5', 'pp3'),
      createDefaultEdge('br5', 'pp4'),
      createDefaultEdge('br5', 'pp5'),
      createDefaultEdge('br5', 'pp6'),
      createDefaultEdge('csc3', 'pp6'),

      // Critical report generation
      createDefaultEdge('pp1', 'rep1'),
      createDefaultEdge('pp2', 'rep1'),
      createDefaultEdge('pp3', 'rep1'),
      createDefaultEdge('pp4', 'rep1'),
      createDefaultEdge('pp5', 'rep1'),
      createDefaultEdge('pp6', 'rep1'),
      createDefaultEdge('rep1', 'rep2'),
      createDefaultEdge('rep2', 'rep3'),
      createDefaultEdge('rep3', 'rep4'),
      createDefaultEdge('rep4', 'rep5'),

      // Final storage + trackers
      createDefaultEdge('rep5', 'db1'),
      createDefaultEdge('rep5', 'db2'),
      createDefaultEdge('rep5', 'db3'),
      createDefaultEdge('db3', 'db4'),
      createDefaultEdge('db4', 'db5'),

      // Reporting / UI
      createDefaultEdge('db1', 'ui1'),
      createDefaultEdge('db2', 'ui1'),
      createDefaultEdge('ui1', 'ui2'),
      createDefaultEdge('db1', 'ui3'),

      // Supporting lambdas (CSC/CSAT/BDA config sync)
      createDefaultEdge('sqs2', 'sup1'),
      createDefaultEdge('sup1', 'csc1'),
      createDefaultEdge('sqs3', 'sup2'),
      createDefaultEdge('sup2', 'csat1'),
      createDefaultEdge('sup3', 'bda1'),
      createDefaultEdge('bda1', 'gf4'),
      createDefaultEdge('csat1', 'gf5'),
    ],
    {
      audience: 'builders',
      useCase: 'U Mobile AICC Post-Call Analytics — end-to-end call recording ingestion, transcription, and Bedrock-driven KPI scoring',
      launchPriority: 5,
      featured: true,
      difficulty: 'advanced',
      outcome: 'A complete view of Genesys ingestion, the 3-Lambda + SQS chain, EKS/FastAPI scoring, Bedrock CR1/CR2 KPI logic, and DynamoDB storage/reporting for PCA',
      replacementHints: ['AWS region (ap-northeast-1)', 'Bedrock model IDs', 'DynamoDB table names', 'SQS queue URLs'],
    }
  ),
];

export function createStarterTemplateRegistry(): TemplateRegistry {
  return createTemplateRegistry(STARTER_TEMPLATE_MANIFESTS);
}
