export const CATEGORIES = [
  { id:"arrays", label:"Arrays", color:"#3b82f6", emoji:"🔢", problems:[
    {id:"1-two-sum",title:"Two Sum",difficulty:"Easy"},
    {id:"1004-max-consecutive-ones-iii",title:"Max Consecutive Ones III",difficulty:"Medium"},
    {id:"11-container-with-most-water",title:"Container With Most Water",difficulty:"Medium"},
    {id:"121-best-time-buy-sell-stock",title:"Best Time to Buy & Sell Stock",difficulty:"Easy"},
    {id:"128-longest-consecutive-sequence",title:"Longest Consecutive Sequence",difficulty:"Medium"},
    {id:"1470-shuffle-the-array",title:"Shuffle the Array",difficulty:"Easy"},
    {id:"1480-running-sum",title:"Running Sum of 1D Array",difficulty:"Easy"},
    {id:"15-three-sum",title:"3Sum",difficulty:"Medium"},
    {id:"167-two-sum-ii",title:"Two Sum II",difficulty:"Medium"},
    {id:"1672-richest-customer-wealth",title:"Richest Customer Wealth",difficulty:"Easy"},
    {id:"169-majority-element",title:"Majority Element",difficulty:"Easy"},
    {id:"189-rotate-array",title:"Rotate Array",difficulty:"Medium"},
    {id:"1929-concatenation-of-array",title:"Concatenation of Array",difficulty:"Easy"},
    {id:"209-min-size-subarray-sum",title:"Minimum Size Subarray Sum",difficulty:"Medium"},
    {id:"217-contains-duplicate",title:"Contains Duplicate",difficulty:"Easy"},
    {id:"2239-find-closest-number",title:"Find Closest Number to Zero",difficulty:"Easy"},
    {id:"238-product-except-self",title:"Product of Array Except Self",difficulty:"Medium"},
    {id:"26-remove-duplicates",title:"Remove Duplicates from Sorted Array",difficulty:"Easy"},
    {id:"383-ransom-note",title:"Ransom Note",difficulty:"Easy"},
    {id:"41-first-missing-positive",title:"First Missing Positive",difficulty:"Hard"},
    {id:"42-trapping-rain-water",title:"Trapping Rain Water",difficulty:"Hard"},
    {id:"53-maximum-subarray",title:"Maximum Subarray",difficulty:"Medium"},
    {id:"560-subarray-sum-equals-k",title:"Subarray Sum Equals K",difficulty:"Medium"},
    {id:"643-max-average-subarray",title:"Maximum Average Subarray I",difficulty:"Easy"},
    {id:"75-sort-colors",title:"Sort Colors",difficulty:"Medium"},
    {id:"832-flipping-an-image",title:"Flipping an Image",difficulty:"Easy"},
    {id:"88-merge-sorted-array",title:"Merge Sorted Array",difficulty:"Easy"},
    {id:"977-squares-sorted-array",title:"Squares of a Sorted Array",difficulty:"Easy"},
  ]},
  { id:"backtracking", label:"Backtracking", color:"#f59e0b", emoji:"🔙", problems:[
    {id:"17-letter-combinations-phone",title:"Letter Combinations of Phone Number",difficulty:"Medium"},
    {id:"22-generate-parentheses",title:"Generate Parentheses",difficulty:"Medium"},
    {id:"37-sudoku-solver",title:"Sudoku Solver",difficulty:"Hard"},
    {id:"39-combination-sum",title:"Combination Sum",difficulty:"Medium"},
    {id:"46-permutations",title:"Permutations",difficulty:"Medium"},
    {id:"51-n-queens",title:"N-Queens",difficulty:"Hard"},
    {id:"77-combinations",title:"Combinations",difficulty:"Medium"},
    {id:"78-subsets",title:"Subsets",difficulty:"Medium"},
    {id:"90-subsets-ii",title:"Subsets II",difficulty:"Medium"},
  ]},
  { id:"binarysearch", label:"Binary Search", color:"#8b5cf6", emoji:"🔍", problems:[
    {id:"1011-capacity-to-ship-packages",title:"Capacity to Ship Packages Within D Days",difficulty:"Medium"},
    {id:"153-find-minimum-rotated",title:"Find Minimum in Rotated Sorted Array",difficulty:"Medium"},
    {id:"162-find-peak-element",title:"Find Peak Element",difficulty:"Medium"},
    {id:"268-missing-number",title:"Missing Number",difficulty:"Easy"},
    {id:"33-search-rotated-sorted-array",title:"Search in Rotated Sorted Array",difficulty:"Medium"},
    {id:"34-first-last-position",title:"Find First and Last Position of Element",difficulty:"Medium"},
    {id:"35-search-insert-position",title:"Search Insert Position",difficulty:"Easy"},
    {id:"4-median-two-sorted-arrays",title:"Median of Two Sorted Arrays",difficulty:"Hard"},
    {id:"410-split-array-largest-sum",title:"Split Array Largest Sum",difficulty:"Hard"},
    {id:"81-search-rotated-ii",title:"Search in Rotated Sorted Array II",difficulty:"Medium"},
    {id:"875-koko-eating-bananas",title:"Koko Eating Bananas",difficulty:"Medium"},
    {id:"gfg-allocate-minimum-pages",title:"Allocate Minimum Pages",difficulty:"Hard"},
  ]},
  { id:"bitmanipulation", label:"Bit Manipulation", color:"#06b6d4", emoji:"⚡", problems:[
    {id:"137-single-number-ii",title:"Single Number II",difficulty:"Medium"},
    {id:"191-number-of-1-bits",title:"Number of 1 Bits",difficulty:"Easy"},
    {id:"231-power-of-two",title:"Power of Two",difficulty:"Easy"},
    {id:"260-single-number-iii",title:"Single Number III",difficulty:"Medium"},
    {id:"287-find-the-duplicate-number",title:"Find the Duplicate Number",difficulty:"Medium"},
    {id:"338-counting-bits",title:"Counting Bits",difficulty:"Easy"},
    {id:"371-sum-of-two-integers",title:"Sum of Two Integers",difficulty:"Medium"},
    {id:"389-find-the-difference",title:"Find the Difference",difficulty:"Easy"},
  ]},
  { id:"dp", label:"Dynamic Programming", color:"#10b981", emoji:"📊", problems:[
    {id:"1143-longest-common-subsequence",title:"Longest Common Subsequence",difficulty:"Medium"},
    {id:"120-triangle",title:"Triangle",difficulty:"Medium"},
    {id:"152-maximum-product-subarray",title:"Maximum Product Subarray",difficulty:"Medium"},
    {id:"198-house-robber",title:"House Robber",difficulty:"Medium"},
    {id:"213-house-robber-ii",title:"House Robber II",difficulty:"Medium"},
    {id:"300-longest-increasing-subsequence",title:"Longest Increasing Subsequence",difficulty:"Medium"},
    {id:"322-coin-change",title:"Coin Change",difficulty:"Medium"},
    {id:"509-fibonacci-number",title:"Fibonacci Number",difficulty:"Easy"},
    {id:"62-unique-paths",title:"Unique Paths",difficulty:"Medium"},
    {id:"63-unique-paths-ii",title:"Unique Paths II",difficulty:"Medium"},
    {id:"70-climbing-stairs",title:"Climbing Stairs",difficulty:"Easy"},
    {id:"72-edit-distance",title:"Edit Distance",difficulty:"Medium"},
    {id:"746-min-cost-climbing-stairs",title:"Min Cost Climbing Stairs",difficulty:"Easy"},
    {id:"91-decode-ways",title:"Decode Ways",difficulty:"Medium"},
    {id:"gfg-longest-common-substring",title:"Longest Common Substring",difficulty:"Medium"},
  ]},
  { id:"graph", label:"Graph", color:"#f97316", emoji:"🕸️", problems:[
    {id:"133-clone-graph",title:"Clone Graph",difficulty:"Medium"},
    {id:"1584-min-cost-connect-points",title:"Min Cost to Connect All Points",difficulty:"Medium"},
    {id:"1971-find-path-exists",title:"Find if Path Exists in Graph",difficulty:"Easy"},
    {id:"207-course-schedule",title:"Course Schedule",difficulty:"Medium"},
    {id:"210-course-schedule-ii",title:"Course Schedule II",difficulty:"Medium"},
    {id:"399-evaluate-division",title:"Evaluate Division",difficulty:"Medium"},
    {id:"417-pacific-atlantic",title:"Pacific Atlantic Water Flow",difficulty:"Medium"},
    {id:"743-network-delay-time",title:"Network Delay Time",difficulty:"Medium"},
    {id:"787-cheapest-flights-k-stops",title:"Cheapest Flights Within K Stops",difficulty:"Medium"},
    {id:"994-rotting-oranges",title:"Rotting Oranges",difficulty:"Medium"},
    {id:"gfg-is-graph-a-tree",title:"Is Graph a Tree?",difficulty:"Medium"},
  ]},
  { id:"greedy", label:"Greedy", color:"#ec4899", emoji:"💡", problems:[
    {id:"134-gas-station",title:"Gas Station",difficulty:"Medium"},
    {id:"135-candy",title:"Candy",difficulty:"Hard"},
    {id:"45-jump-game-ii",title:"Jump Game II",difficulty:"Medium"},
    {id:"55-jump-game",title:"Jump Game",difficulty:"Medium"},
    {id:"gfg-minimum-platforms",title:"Minimum Platforms",difficulty:"Medium"},
  ]},
  { id:"heap", label:"Heap / Priority Queue", color:"#84cc16", emoji:"🏔️", problems:[
    {id:"1046-last-stone-weight",title:"Last Stone Weight",difficulty:"Easy"},
    {id:"215-kth-largest-element",title:"Kth Largest Element in Array",difficulty:"Medium"},
    {id:"295-find-median-data-stream",title:"Find Median from Data Stream",difficulty:"Hard"},
    {id:"347-top-k-frequent-elements",title:"Top K Frequent Elements",difficulty:"Medium"},
    {id:"621-task-scheduler",title:"Task Scheduler",difficulty:"Medium"},
    {id:"973-k-closest-points",title:"K Closest Points to Origin",difficulty:"Medium"},
  ]},
  { id:"intervals", label:"Intervals", color:"#f43f5e", emoji:"📏", problems:[
    {id:"253-meeting-rooms-ii",title:"Meeting Rooms II",difficulty:"Medium"},
    {id:"435-non-overlapping-intervals",title:"Non-overlapping Intervals",difficulty:"Medium"},
    {id:"452-minimum-arrows-balloons",title:"Minimum Number of Arrows to Burst Balloons",difficulty:"Medium"},
    {id:"56-merge-intervals",title:"Merge Intervals",difficulty:"Medium"},
    {id:"57-insert-interval",title:"Insert Interval",difficulty:"Medium"},
  ]},
  { id:"linkedlist", label:"Linked List", color:"#a78bfa", emoji:"🔗", problems:[
    {id:"138-copy-list-with-random-pointer",title:"Copy List with Random Pointer",difficulty:"Medium"},
    {id:"141-linked-list-cycle",title:"Linked List Cycle",difficulty:"Easy"},
    {id:"143-reorder-list",title:"Reorder List",difficulty:"Medium"},
    {id:"19-remove-nth-from-end",title:"Remove Nth Node From End of List",difficulty:"Medium"},
    {id:"2-add-two-numbers",title:"Add Two Numbers",difficulty:"Medium"},
    {id:"202-happy-number",title:"Happy Number",difficulty:"Easy"},
    {id:"206-reverse-linked-list",title:"Reverse Linked List",difficulty:"Easy"},
    {id:"23-merge-k-sorted-lists",title:"Merge K Sorted Lists",difficulty:"Hard"},
    {id:"234-palindrome-linked-list",title:"Palindrome Linked List",difficulty:"Easy"},
    {id:"25-reverse-nodes-in-k-group",title:"Reverse Nodes in K-Group",difficulty:"Hard"},
    {id:"83-remove-duplicates-sorted-list",title:"Remove Duplicates from Sorted List",difficulty:"Easy"},
    {id:"876-middle-of-linked-list",title:"Middle of the Linked List",difficulty:"Easy"},
    {id:"92-reverse-linked-list-ii",title:"Reverse Linked List II",difficulty:"Medium"},
  ]},
  { id:"matrix", label:"Matrix", color:"#0ea5e9", emoji:"🟦", problems:[
    {id:"200-number-of-islands",title:"Number of Islands",difficulty:"Medium"},
    {id:"240-search-2d-matrix-ii",title:"Search a 2D Matrix II",difficulty:"Medium"},
    {id:"36-valid-sudoku",title:"Valid Sudoku",difficulty:"Medium"},
    {id:"48-rotate-image",title:"Rotate Image",difficulty:"Medium"},
    {id:"54-spiral-matrix",title:"Spiral Matrix",difficulty:"Medium"},
    {id:"59-spiral-matrix-ii",title:"Spiral Matrix II",difficulty:"Medium"},
    {id:"73-set-matrix-zeroes",title:"Set Matrix Zeroes",difficulty:"Medium"},
    {id:"74-search-2d-matrix",title:"Search a 2D Matrix",difficulty:"Medium"},
    {id:"79-word-search",title:"Word Search",difficulty:"Medium"},
  ]},
  { id:"queue", label:"Queue", color:"#fb923c", emoji:"📦", problems:[
    {id:"gfg-reverse-first-k-elements-queue",title:"Reverse First K Elements of Queue",difficulty:"Easy"},
  ]},
  { id:"stack", label:"Stack", color:"#e879f9", emoji:"📚", problems:[
    {id:"150-evaluate-rpn",title:"Evaluate Reverse Polish Notation",difficulty:"Medium"},
    {id:"155-min-stack",title:"Min Stack",difficulty:"Medium"},
    {id:"20-valid-parentheses",title:"Valid Parentheses",difficulty:"Easy"},
    {id:"224-basic-calculator",title:"Basic Calculator",difficulty:"Hard"},
    {id:"496-next-greater-element-i",title:"Next Greater Element I",difficulty:"Easy"},
    {id:"739-daily-temperatures",title:"Daily Temperatures",difficulty:"Medium"},
    {id:"84-largest-rectangle-histogram",title:"Largest Rectangle in Histogram",difficulty:"Hard"},
    {id:"85-maximal-rectangle",title:"Maximal Rectangle",difficulty:"Hard"},
  ]},
  { id:"strings", label:"Strings", color:"#34d399", emoji:"🔤", problems:[
    {id:"1189-maximum-number-of-balloons",title:"Maximum Number of Balloons",difficulty:"Easy"},
    {id:"125-valid-palindrome",title:"Valid Palindrome",difficulty:"Easy"},
    {id:"13-roman-to-integer",title:"Roman to Integer",difficulty:"Easy"},
    {id:"14-longest-common-prefix",title:"Longest Common Prefix",difficulty:"Easy"},
    {id:"205-isomorphic-strings",title:"Isomorphic Strings",difficulty:"Easy"},
    {id:"242-valid-anagram",title:"Valid Anagram",difficulty:"Easy"},
    {id:"271-encode-decode-strings",title:"Encode and Decode Strings",difficulty:"Medium"},
    {id:"3-longest-substring-without-repeating",title:"Longest Substring Without Repeating Characters",difficulty:"Medium"},
    {id:"344-reverse-string",title:"Reverse String",difficulty:"Easy"},
    {id:"424-longest-repeating-char-replacement",title:"Longest Repeating Character Replacement",difficulty:"Medium"},
    {id:"438-find-all-anagrams",title:"Find All Anagrams in a String",difficulty:"Medium"},
    {id:"49-group-anagrams",title:"Group Anagrams",difficulty:"Medium"},
    {id:"5-longest-palindromic-substring",title:"Longest Palindromic Substring",difficulty:"Medium"},
    {id:"567-permutation-in-string",title:"Permutation in String",difficulty:"Medium"},
    {id:"647-palindromic-substrings",title:"Palindromic Substrings",difficulty:"Medium"},
    {id:"680-valid-palindrome-ii",title:"Valid Palindrome II",difficulty:"Easy"},
    {id:"76-minimum-window-substring",title:"Minimum Window Substring",difficulty:"Hard"},
  ]},
  { id:"tree", label:"Tree", color:"#fbbf24", emoji:"🌳", problems:[
    {id:"101-symmetric-tree",title:"Symmetric Tree",difficulty:"Easy"},
    {id:"102-binary-tree-level-order",title:"Binary Tree Level Order Traversal",difficulty:"Medium"},
    {id:"103-zigzag-level-order",title:"Binary Tree Zigzag Level Order Traversal",difficulty:"Medium"},
    {id:"104-maximum-depth",title:"Maximum Depth of Binary Tree",difficulty:"Easy"},
    {id:"105-construct-from-preorder-inorder",title:"Construct Binary Tree from Preorder & Inorder",difficulty:"Medium"},
    {id:"108-sorted-array-to-bst",title:"Convert Sorted Array to Binary Search Tree",difficulty:"Easy"},
    {id:"110-balanced-binary-tree",title:"Balanced Binary Tree",difficulty:"Easy"},
    {id:"112-path-sum",title:"Path Sum",difficulty:"Easy"},
    {id:"113-path-sum-ii",title:"Path Sum II",difficulty:"Medium"},
    {id:"114-flatten-to-linked-list",title:"Flatten Binary Tree to Linked List",difficulty:"Medium"},
    {id:"124-binary-tree-max-path-sum",title:"Binary Tree Maximum Path Sum",difficulty:"Hard"},
    {id:"129-sum-root-to-leaf-numbers",title:"Sum Root to Leaf Numbers",difficulty:"Medium"},
    {id:"199-right-side-view",title:"Binary Tree Right Side View",difficulty:"Medium"},
    {id:"226-invert-binary-tree",title:"Invert Binary Tree",difficulty:"Easy"},
    {id:"230-kth-smallest-bst",title:"Kth Smallest Element in a BST",difficulty:"Medium"},
    {id:"236-lowest-common-ancestor",title:"Lowest Common Ancestor of Binary Tree",difficulty:"Medium"},
    {id:"297-serialize-deserialize-binary-tree",title:"Serialize and Deserialize Binary Tree",difficulty:"Hard"},
    {id:"543-diameter-of-binary-tree",title:"Diameter of Binary Tree",difficulty:"Easy"},
    {id:"637-average-of-levels",title:"Average of Levels in Binary Tree",difficulty:"Easy"},
    {id:"98-validate-bst",title:"Validate Binary Search Tree",difficulty:"Medium"},
  ]},
];
