import React, { useMemo, useState } from "react";
import { Button, Console, LabFrame, Meter, Panel, Tag } from "./LabKit";

const cap = (n, a = 0, b = 100) => Math.max(a, Math.min(b, n));

/* ───────────────────────── 14 · Trace Detective ───────────────────────── */
const TRACE_CASES = [
  { id: "refund", label: "The duplicate refund", symptom: "Agent said ‘done’ once; two refunds exist.", root: "retry", spans: [
    { t: "00ms", name: "request", detail: "refund order 1842", dur: 8, status: "ok" }, { t: "184ms", name: "lookup_order", detail: "status=delivered, total=84.20", dur: 92, status: "ok" },
    { t: "612ms", name: "create_refund", detail: "HTTP 504 after upstream commit", dur: 2201, status: "warn" }, { t: "2918ms", name: "retry", detail: "same arguments, no idempotency key", dur: 211, status: "bad" }, { t: "3190ms", name: "outcome", detail: "rf_928 and rf_929 both settled", dur: 33, status: "bad" } ] },
  { id: "rag", label: "The wrong policy", symptom: "Answer cites v4 but applies v2’s 14-day rule.", root: "context", spans: [
    { t: "00ms", name: "query", detail: "refund window for damaged delivery", dur: 11, status: "ok" }, { t: "92ms", name: "retrieve", detail: "v4 score .91; v2 score .87", dur: 81, status: "warn" },
    { t: "203ms", name: "rerank", detail: "v2 placed first due exact phrase match", dur: 44, status: "bad" }, { t: "481ms", name: "context", detail: "both passages, version metadata removed", dur: 9, status: "bad" }, { t: "1040ms", name: "answer", detail: "claims 14 days; citation label points to v4", dur: 559, status: "bad" } ] },
  { id: "slow", label: "The 40-second answer", symptom: "No error, but routine support takes 40.8 seconds.", root: "fanout", spans: [
    { t: "00ms", name: "plan", detail: "search every connected source", dur: 321, status: "warn" }, { t: "340ms", name: "tool fan-out", detail: "28 parallel calls, pool size 4", dur: 18400, status: "bad" },
    { t: "18.9s", name: "rate limit", detail: "9 calls retry after 2s", dur: 8400, status: "bad" }, { t: "27.4s", name: "model", detail: "context includes 1.2MB tool output", dur: 12900, status: "bad" }, { t: "40.8s", name: "answer", detail: "only one source used", dur: 27, status: "ok" } ] },
];
const HYPOTHESES = [{ id: "retry", label: "Non-idempotent retry" }, { id: "context", label: "Version metadata lost" }, { id: "fanout", label: "Unbounded tool fan-out" }, { id: "model", label: "Base model regression" }];

export function TraceDetectiveLab() {
  const [caseId, setCaseId] = useState("refund"); const [span, setSpan] = useState(2); const [hypothesis, setHypothesis] = useState(null); const [submitted, setSubmitted] = useState(false); const [clues, setClues] = useState([]);
  const c = TRACE_CASES.find((x) => x.id === caseId); const active = c.spans[span]; const correct = hypothesis === c.root;
  const openCase = (id) => { setCaseId(id); setSpan(0); setHypothesis(null); setSubmitted(false); setClues([]); };
  const addClue = () => { const text = `${active.name}: ${active.detail}`; if (!clues.includes(text)) setClues((x) => [...x, text]); };
  return <LabFrame number="14" kicker="Observability" title="Trace Detective" subtitle="Debug the Trajectory, Not the Last Sentence" accent="#334155" soft="#eef2f6" lead="Inspect spans, collect evidence, and accuse a root cause. The correct answer must explain the environmental outcome." stats={[{ label: "Case", value: `${TRACE_CASES.findIndex((x) => x.id === caseId) + 1}/3` }, { label: "Clues", value: clues.length }, { label: "Verdict", value: submitted ? correct ? "Solved" : "Wrong" : "Open" }]}>
    <div className="lx-grid">
      <Panel title="Incident queue" subtitle="Three production mysteries"><div className="lx-pb">{TRACE_CASES.map((x) => <button key={x.id} onClick={() => openCase(x.id)} className={`lx-card click ${x.id === caseId ? "on" : ""}`} style={{ width: "100%", textAlign: "left" }}><Tag tone={x.id === "refund" ? "bad" : "warn"}>P{x.id === "refund" ? 1 : 2}</Tag><b style={{ display: "block", marginTop: 6 }}>{x.label}</b><p>{x.symptom}</p></button>)}<div className="lx-label">Evidence board</div>{clues.length ? clues.map((x) => <div className="lx-token" style={{ display: "flex", marginBottom: 5 }} key={x}>{x}</div>) : <div className="lx-empty">Pin span evidence here.</div>}</div></Panel>
      <Panel title="Trace timeline" subtitle="Click a span to inspect its inputs and outcome"><div className="lx-pb"><table className="lx-table"><thead><tr><th>Start</th><th>Span</th><th>Duration</th><th>Status</th></tr></thead><tbody>{c.spans.map((s, i) => <tr className="click" onClick={() => setSpan(i)} style={i === span ? { background: "var(--as)" } : undefined} key={`${s.t}-${s.name}`}><td>{s.t}</td><td><b>{s.name}</b><br /><span style={{ color: "var(--mut)" }}>{s.detail}</span></td><td>{s.dur}ms</td><td><Tag tone={s.status === "bad" ? "bad" : s.status === "warn" ? "warn" : "good"}>{s.status}</Tag></td></tr>)}</tbody></table><div className="lx-card on" style={{ marginTop: 10 }}><div className="lx-row"><Tag tone={active.status === "bad" ? "bad" : "a"}>{active.name}</Tag><b className="lx-grow">Span inspector</b><Button small onClick={addClue}>Pin as evidence</Button></div><p>{active.detail}</p><div className="lx-console" style={{ minHeight: 70, marginTop: 8 }}><span className={active.status === "bad" ? "err" : "ok"}>{JSON.stringify({ trace_id: `tr_${caseId}_1842`, span: active.name, duration_ms: active.dur, outcome: active.detail }, null, 2)}</span></div></div></div></Panel>
      <Panel title="Root-cause bench" subtitle="Commit a falsifiable diagnosis"><div className="lx-pb">{HYPOTHESES.map((h) => <button key={h.id} onClick={() => { setHypothesis(h.id); setSubmitted(false); }} className={`lx-card click ${hypothesis === h.id ? "on" : ""}`} style={{ width: "100%", textAlign: "left" }}><b>{h.label}</b></button>)}<Button primary style={{ width: "100%" }} disabled={!hypothesis} onClick={() => setSubmitted(true)}>Submit diagnosis</Button>{submitted && <div className={`lx-callout ${correct ? "good" : "bad"}`} style={{ marginTop: 9 }}>{correct ? `Solved. ${HYPOTHESES.find((h) => h.id === c.root).label} explains the trace and final state.` : "That hypothesis does not explain every pinned outcome. Inspect the first span where state diverges."}</div>}<div className="lx-divider" /><Meter label="Evidence completeness" value={clues.length / 3 * 100} /><Meter label="Causal confidence" value={submitted ? correct ? 96 : 28 : clues.length * 22} /></div></Panel>
    </div>
  </LabFrame>;
}

/* ───────────────────────── 15 · Structured Output Repair ───────────────────────── */
const OUTPUT_SAMPLES = {
  invoice: { label: "Invoice extraction", text: `{"invoice_id":"INV-84","currency":"$","subtotal":120,"tax":9.6,"total":128,"items":[{"name":"Support","qty":"1","price":120}]}`, rules: "currency must be ISO; qty number; subtotal + tax = total" },
  api: { label: "API request", text: `{"version":"v1","action":"refund","order_id":"1842","amount":-84.2,"notify":"yes"}`, rules: "version v2; order_id integer; amount positive; notify boolean" },
  classify: { label: "Classification", text: `{"labels":["billing","urgent-ish"],"confidence":1.24,"unknown":false}`, rules: "known enums only; confidence 0..1; unknown for ambiguity" },
};

function validateOutput(kind, text) {
  let value; try { value = JSON.parse(text); } catch (e) { return [{ path: "$", msg: `JSON parse error: ${e.message}`, fix: null }]; }
  const errors = [];
  if (kind === "invoice") { if (!/^[A-Z]{3}$/.test(value.currency || "")) errors.push({ path: "$.currency", msg: "Expected ISO 4217 code", fix: ["currency", "USD"] }); if (typeof value.items?.[0]?.qty !== "number") errors.push({ path: "$.items[0].qty", msg: "Expected number", fix: ["qty", 1] }); if (Math.abs((value.subtotal + value.tax) - value.total) > .001) errors.push({ path: "$.total", msg: "Arithmetic invariant failed", fix: ["total", value.subtotal + value.tax] }); }
  if (kind === "api") { if (value.version !== "v2") errors.push({ path: "$.version", msg: "Unsupported contract version", fix: ["version", "v2"] }); if (!Number.isInteger(value.order_id)) errors.push({ path: "$.order_id", msg: "Expected integer", fix: ["order_id", Number(value.order_id)] }); if (!(value.amount > 0)) errors.push({ path: "$.amount", msg: "Must be positive", fix: ["amount", Math.abs(value.amount)] }); if (typeof value.notify !== "boolean") errors.push({ path: "$.notify", msg: "Expected boolean", fix: ["notify", value.notify === "yes"] }); }
  if (kind === "classify") { if ((value.labels || []).some((x) => !["billing", "urgent", "technical"].includes(x))) errors.push({ path: "$.labels", msg: "Unknown enum value", fix: ["labels", (value.labels || []).filter((x) => ["billing", "urgent", "technical"].includes(x))] }); if (value.confidence < 0 || value.confidence > 1) errors.push({ path: "$.confidence", msg: "Must be between 0 and 1", fix: ["confidence", 1] }); }
  return errors;
}

export function StructuredOutputRepairLab() {
  const [kind, setKind] = useState("invoice"); const [text, setText] = useState(OUTPUT_SAMPLES.invoice.text); const [errors, setErrors] = useState([]); const [ran, setRan] = useState(false); const [consumed, setConsumed] = useState(false);
  const choose = (k) => { setKind(k); setText(OUTPUT_SAMPLES[k].text); setErrors([]); setRan(false); setConsumed(false); };
  const validate = () => { setErrors(validateOutput(kind, text)); setRan(true); setConsumed(false); };
  const applyFix = (fix) => { let value; try { value = JSON.parse(text); } catch { return; } const [field, next] = fix; if (field === "qty") value.items[0].qty = next; else value[field] = next; setText(JSON.stringify(value, null, 2)); setRan(false); };
  return <LabFrame number="15" kicker="Output contracts" title="Structured Output Repair Shop" subtitle="Parse, Validate, Repair, Consume" accent="#0891b2" soft="#e8f8fc" lead="Work on malformed model output directly. Syntax, schema, semantic invariants, and downstream safety are separate gates." stats={[{ label: "Format", value: ran ? errors.some((e) => e.path === "$" ) ? "Broken" : "JSON" : "—" }, { label: "Errors", value: ran ? errors.length : "—" }, { label: "Consumer", value: consumed ? "Accepted" : "Locked" }]}>
    <div className="lx-grid">
      <Panel title="Repair jobs" subtitle="Each contract fails differently"><div className="lx-pb">{Object.entries(OUTPUT_SAMPLES).map(([id, s]) => <button key={id} onClick={() => choose(id)} className={`lx-card click ${kind === id ? "on" : ""}`} style={{ width: "100%", textAlign: "left" }}><b>{s.label}</b><p>{s.rules}</p></button>)}</div></Panel>
      <Panel title="Model output editor" subtitle="Edit the payload or apply targeted patches" action={<Button primary small onClick={validate}>Validate output</Button>}><div className="lx-pb"><textarea aria-label="Structured model output" className="lx-textarea" style={{ minHeight: 340 }} value={text} onChange={(e) => { setText(e.target.value); setRan(false); setConsumed(false); }} /><div className="lx-label">Validation pipeline</div><div className="lx-row wrap">{["Parse", "Schema", "Semantics", "Consumer"].map((x, i) => <Tag key={x} tone={!ran ? "" : errors.length === 0 || (i === 0 && !errors.some((e) => e.path === "$")) ? "good" : i === 3 ? "" : "bad"}>{i + 1}. {x}</Tag>)}</div></div></Panel>
      <Panel title="Validation report" subtitle="Errors point to a path and recovery"><div className="lx-pb">{!ran ? <div className="lx-empty">Run validation to inspect the payload.</div> : errors.length ? errors.map((e) => <div className="lx-card bad" key={`${e.path}-${e.msg}`}><Tag tone="bad">{e.path}</Tag><p>{e.msg}</p>{e.fix && <Button small onClick={() => applyFix(e.fix)}>Apply targeted patch</Button>}</div>) : <><div className="lx-callout good">All format, schema, and semantic checks pass.</div><Button primary style={{ width: "100%", marginTop: 9 }} onClick={() => setConsumed(true)}>Send to downstream consumer</Button>{consumed && <div className="lx-console" style={{ marginTop: 9 }}><span className="ok">consumer.accepted · typed object committed</span></div>}</>}<div className="lx-divider" /><Meter label="Contract health" value={!ran ? 0 : errors.length ? cap(100 - errors.length * 24) : 100} /></div></Panel>
    </div>
  </LabFrame>;
}

/* ───────────────────────── 16 · Model Router ───────────────────────── */
const ROUTER_TRAFFIC = [
  { id: 1, task: "Reset my password", complexity: 12, risk: 10, modality: "text", ideal: "fast" }, { id: 2, task: "Review this auth diff for a race", complexity: 82, risk: 88, modality: "code", ideal: "reason" },
  { id: 3, task: "Extract totals from this receipt", complexity: 42, risk: 25, modality: "vision", ideal: "vision" }, { id: 4, task: "Summarize our refund policy", complexity: 34, risk: 45, modality: "text", ideal: "fast" },
  { id: 5, task: "Approve a $20k wire transfer", complexity: 55, risk: 98, modality: "text", ideal: "human" }, { id: 6, task: "Translate a product title", complexity: 18, risk: 8, modality: "text", ideal: "fast" },
  { id: 7, task: "Debug distributed transaction logs", complexity: 91, risk: 72, modality: "code", ideal: "reason" }, { id: 8, task: "Read handwriting on an intake form", complexity: 65, risk: 55, modality: "vision", ideal: "vision" },
];
const MODEL_META = { fast: { label: "Fast model", cost: .2, latency: 380 }, reason: { label: "Reasoning model", cost: 2.8, latency: 4100 }, vision: { label: "Vision model", cost: 1.1, latency: 1800 }, human: { label: "Human review", cost: 8, latency: 12000 } };

export function ModelRouterLab() {
  const [threshold, setThreshold] = useState(62); const [riskFloor, setRiskFloor] = useState(85); const [vision, setVision] = useState(true); const [fallback, setFallback] = useState(true); const [results, setResults] = useState([]);
  const run = () => setResults(ROUTER_TRAFFIC.map((t) => { let route = t.risk >= riskFloor ? "human" : t.modality === "vision" && vision ? "vision" : t.complexity >= threshold ? "reason" : "fast"; if (!fallback && route === "reason" && t.complexity < threshold + 8) route = "fast"; const pass = route === t.ideal || (t.ideal === "fast" && route === "reason"); return { ...t, route, pass, ...MODEL_META[route] }; }));
  const cost = results.reduce((s, r) => s + r.cost, 0); const latency = results.length ? Math.round(results.reduce((s, r) => s + r.latency, 0) / results.length) : 0; const accuracy = results.length ? results.filter((r) => r.pass).length / results.length * 100 : 0;
  return <LabFrame number="16" kicker="Inference architecture" title="Model Router" subtitle="Right Model, Right Task" accent="#9333ea" soft="#f6ecff" lead="Build routing policy with thresholds and specialist paths, then replay a mixed traffic batch and inspect every decision." stats={[{ label: "Route accuracy", value: results.length ? `${Math.round(accuracy)}%` : "—" }, { label: "Batch cost", value: results.length ? `$${cost.toFixed(2)}` : "—" }, { label: "Avg latency", value: results.length ? `${latency}ms` : "—" }]}>
    <div className="lx-grid two">
      <Panel title="Routing policy builder" subtitle="Tune the decision boundaries"><div className="lx-pb"><label className="lx-label" htmlFor="complexity">Reasoning threshold · {threshold}</label><input id="complexity" className="lx-range" type="range" min="20" max="90" value={threshold} onChange={(e) => { setThreshold(Number(e.target.value)); setResults([]); }} /><label className="lx-label" htmlFor="risk">Human-review risk floor · {riskFloor}</label><input id="risk" className="lx-range" type="range" min="50" max="100" value={riskFloor} onChange={(e) => { setRiskFloor(Number(e.target.value)); setResults([]); }} /><div className="lx-row wrap" style={{ marginTop: 12 }}><button onClick={() => { setVision((x) => !x); setResults([]); }} className={`lx-card click ${vision ? "on" : ""}`}><b>Vision specialist</b><p>{vision ? "enabled" : "disabled"}</p></button><button onClick={() => { setFallback((x) => !x); setResults([]); }} className={`lx-card click ${fallback ? "on" : ""}`}><b>Strong fallback</b><p>{fallback ? "enabled" : "disabled"}</p></button></div><Button primary style={{ width: "100%" }} onClick={run}>Replay 8 requests</Button><div className="lx-divider" /><Meter label="Quality" value={accuracy} /><Meter label="Cost efficiency" value={results.length ? cap(100 - cost * 3) : 0} /><Meter label="Latency efficiency" value={results.length ? cap(100 - latency / 140) : 0} /></div></Panel>
      <Panel title="Traffic replay" subtitle="Every row explains the route"><div className="lx-pb" style={{ overflowX: "auto" }}><table className="lx-table"><thead><tr><th>Request</th><th>Features</th><th>Route</th><th>Cost</th><th>Result</th></tr></thead><tbody>{ROUTER_TRAFFIC.map((t, i) => { const r = results[i]; return <tr key={t.id}><td><b>{t.task}</b></td><td>C{t.complexity} · R{t.risk} · {t.modality}</td><td>{r ? <Tag tone={r.route === "human" ? "warn" : "a"}>{r.label}</Tag> : "—"}</td><td>{r ? `$${r.cost.toFixed(2)}` : "—"}</td><td>{r ? <Tag tone={r.pass ? "good" : "bad"}>{r.pass ? "fit" : `wanted ${t.ideal}`}</Tag> : "—"}</td></tr>; })}</tbody></table></div></Panel>
    </div>
  </LabFrame>;
}

/* ───────────────────────── 17 · Grounding Court ───────────────────────── */
const CLAIMS = [
  { id: "window", text: "Damaged goods can be returned within 30 days.", truth: ["v4"], verdict: "support" },
  { id: "fee", text: "All returns incur a 15% restocking fee.", truth: [], verdict: "reject" },
  { id: "region", text: "The policy applies globally without exceptions.", truth: ["eu"], verdict: "qualify" },
];
const SOURCES = [
  { id: "v4", title: "Returns Policy v4", authority: "Primary", fresh: "2026-06", snippet: "Damaged items are eligible for return within 30 calendar days of delivery." },
  { id: "v2", title: "Returns Policy v2", authority: "Superseded", fresh: "2024-02", snippet: "Returns must be initiated within 14 days. A restocking fee may apply to opened electronics." },
  { id: "blog", title: "Retail blog summary", authority: "Secondary", fresh: "2025-11", snippet: "The company is known for flexible returns in most markets." },
  { id: "eu", title: "EU regional addendum", authority: "Primary", fresh: "2026-05", snippet: "Statutory withdrawal rights and exclusions vary for EU customers and override the global policy." },
];

export function GroundingCourtLab() {
  const [claimId, setClaimId] = useState("window"); const [links, setLinks] = useState({}); const [verdicts, setVerdicts] = useState({}); const [submitted, setSubmitted] = useState(false);
  const claim = CLAIMS.find((c) => c.id === claimId); const chosen = links[claimId] || [];
  const link = (id) => setLinks((all) => ({ ...all, [claimId]: chosen.includes(id) ? chosen.filter((x) => x !== id) : [...chosen, id] }));
  const scored = CLAIMS.map((c) => { const src = links[c.id] || []; const evidence = c.truth.length ? c.truth.every((x) => src.includes(x)) : src.length === 0; return evidence && verdicts[c.id] === c.verdict; }); const score = scored.filter(Boolean).length / CLAIMS.length * 100;
  return <LabFrame number="17" kicker="Grounded generation" title="Grounding Court" subtitle="Claim, Evidence, Verdict" accent="#a16207" soft="#fff8df" lead="Adjudicate claims one by one. Link authoritative passages, account for version and region, then issue a supported, qualified, or rejected verdict." stats={[{ label: "Claims", value: `${Object.keys(verdicts).length}/3` }, { label: "Evidence links", value: Object.values(links).flat().length }, { label: "Court score", value: submitted ? `${Math.round(score)}%` : "—" }]}>
    <div className="lx-grid">
      <Panel title="Claims docket" subtitle="Select a material proposition"><div className="lx-pb">{CLAIMS.map((c, i) => <button key={c.id} onClick={() => setClaimId(c.id)} className={`lx-card click ${c.id === claimId ? "on" : ""} ${submitted ? scored[i] ? "good" : "bad" : ""}`} style={{ width: "100%", textAlign: "left" }}><Tag>C{i + 1}</Tag><p style={{ color: "var(--ink)" }}>{c.text}</p>{verdicts[c.id] && <Tag tone="a">{verdicts[c.id]}</Tag>}</button>)}</div></Panel>
      <Panel title="Evidence library" subtitle="Link passages to the active claim"><div className="lx-pb">{SOURCES.map((s) => <button key={s.id} onClick={() => link(s.id)} className={`lx-card click ${chosen.includes(s.id) ? "on" : ""}`} style={{ width: "100%", textAlign: "left" }}><div className="lx-row"><Tag tone={s.authority === "Primary" ? "good" : s.authority === "Superseded" ? "bad" : "warn"}>{s.authority}</Tag><b className="lx-grow">{s.title}</b><Tag>{s.fresh}</Tag></div><p>“{s.snippet}”</p><span className="lx-kbd">{chosen.includes(s.id) ? "LINKED" : "LINK"}</span></button>)}</div></Panel>
      <Panel title="Judgment bench" subtitle="Evidence and verdict must agree"><div className="lx-pb"><div className="lx-callout">Active claim: {claim.text}</div><div className="lx-label">Issue verdict</div>{[{ id: "support", label: "Supported" }, { id: "qualify", label: "Qualified / scoped" }, { id: "reject", label: "Reject as unsupported" }].map((v) => <button key={v.id} onClick={() => { setVerdicts((x) => ({ ...x, [claimId]: v.id })); setSubmitted(false); }} className={`lx-card click ${verdicts[claimId] === v.id ? "on" : ""}`} style={{ width: "100%", textAlign: "left" }}><b>{v.label}</b></button>)}<Button primary style={{ width: "100%" }} disabled={Object.keys(verdicts).length < 3} onClick={() => setSubmitted(true)}>Submit all judgments</Button>{submitted && <div className={`lx-callout ${score === 100 ? "good" : "bad"}`} style={{ marginTop: 9 }}>{score === 100 ? "Court complete: every claim has adequate evidence and the correct scope." : `${scored.filter(Boolean).length}/3 judgments survive appeal. Revisit red docket items.`}</div>}<Meter label="Grounding precision" value={submitted ? score : Object.keys(verdicts).length / 3 * 60} /></div></Panel>
    </div>
  </LabFrame>;
}

/* ───────────────────────── 18 · Agent Uncertainty ───────────────────────── */
const UNCERTAINTY_CASES = [
  { q: "Cancel it.", context: "Two active subscriptions exist.", p: .48, best: "ask", why: "The target is ambiguous; one question resolves it." },
  { q: "Is the service down right now?", context: "Status changes minute to minute.", p: .36, best: "search", why: "Fresh external evidence is cheap and necessary." },
  { q: "Send $20,000 to account ending 1190.", context: "Account match confidence is 92%.", p: .92, best: "human", why: "High confidence is insufficient for an irreversible payment." },
  { q: "What is 17 × 24?", context: "Deterministic arithmetic.", p: .99, best: "answer", why: "Answer directly; verification cost exceeds risk." },
  { q: "Which policy applies to this EU customer?", context: "Region known; policy versions conflict.", p: .63, best: "search", why: "Retrieve the current regional addendum." },
  { q: "Book the earlier flight.", context: "Two flights depart at 08:10.", p: .51, best: "ask", why: "Clarify flight number before a consequential booking." },
];
const ACTIONS = [{ id: "answer", label: "Answer" }, { id: "search", label: "Verify / search" }, { id: "ask", label: "Ask one question" }, { id: "human", label: "Escalate" }];

export function AgentUncertaintyLab() {
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState([]); const [confidence, setConfidence] = useState(70); const current = UNCERTAINTY_CASES[index];
  const decide = (action) => { if (answers[index]) return; const correct = action === current.best; const next = [...answers]; next[index] = { action, correct, stated: confidence }; setAnswers(next); };
  const result = answers[index]; const accuracy = answers.filter(Boolean).length ? answers.filter((x) => x?.correct).length / answers.filter(Boolean).length * 100 : 0; const brier = answers.filter(Boolean).length ? answers.filter(Boolean).reduce((s, x) => s + Math.pow(x.stated / 100 - (x.correct ? 1 : 0), 2), 0) / answers.filter(Boolean).length : 0;
  return <LabFrame number="18" kicker="Calibration" title="Agent Uncertainty Lab" subtitle="Choose the Next Action, Not a Confident Tone" accent="#be185d" soft="#fff0f6" lead="Work through ambiguous, fresh, and consequential cases. Set confidence, choose an action, and watch calibration diverge from correctness." stats={[{ label: "Case", value: `${index + 1}/6` }, { label: "Policy accuracy", value: answers.length ? `${Math.round(accuracy)}%` : "—" }, { label: "Brier loss", value: answers.length ? brier.toFixed(2) : "—" }]}>
    <div className="lx-grid wide">
      <Panel title="Decision chamber" subtitle="What should the agent do next?"><div className="lx-pb"><Tag tone="a">Case {index + 1}</Tag><h2 style={{ fontSize: 24, margin: "12px 0 5px" }}>{current.q}</h2><p style={{ color: "var(--mut)" }}>{current.context}</p><div className="lx-label">Agent confidence · {confidence}%</div><input aria-label="Agent confidence" type="range" className="lx-range" min="10" max="99" value={confidence} onChange={(e) => setConfidence(Number(e.target.value))} disabled={!!result} /><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 9, marginTop: 15 }}>{ACTIONS.map((a) => <Button key={a.id} primary={result?.action === a.id} onClick={() => decide(a.id)} disabled={!!result}>{a.label}</Button>)}</div>{result && <div className={`lx-callout ${result.correct ? "good" : "bad"}`} style={{ marginTop: 12 }}><b>{result.correct ? "Good policy decision." : `Unsafe or inefficient choice. Best action: ${current.best}.`}</b><br />{current.why}</div>}<div className="lx-row" style={{ marginTop: 10 }}><Button onClick={() => { setIndex(Math.max(0, index - 1)); setConfidence(70); }} disabled={index === 0}>Previous</Button><Button primary onClick={() => { setIndex(Math.min(UNCERTAINTY_CASES.length - 1, index + 1)); setConfidence(70); }} disabled={index === UNCERTAINTY_CASES.length - 1}>Next case</Button></div></div></Panel>
      <Panel title="Calibration ledger" subtitle="Confidence is useful only when outcomes agree"><div className="lx-pb"><table className="lx-table"><thead><tr><th>Case</th><th>Confidence</th><th>Action</th><th>Outcome</th></tr></thead><tbody>{UNCERTAINTY_CASES.map((c, i) => <tr key={c.q} style={i === index ? { background: "var(--as)" } : undefined}><td>{i + 1}. {c.q}</td><td>{answers[i] ? `${answers[i].stated}%` : "—"}</td><td>{answers[i]?.action || "—"}</td><td>{answers[i] ? <Tag tone={answers[i].correct ? "good" : "bad"}>{answers[i].correct ? "fit" : "miss"}</Tag> : "—"}</td></tr>)}</tbody></table><Meter label="Action-policy accuracy" value={accuracy} /><Meter label="Calibration quality" value={answers.length ? (1 - brier) * 100 : 0} /></div></Panel>
    </div>
  </LabFrame>;
}

/* ───────────────────────── 19 · Prompt Cache Workshop ───────────────────────── */
const CACHE_BLOCKS = [
  { id: "policy", label: "System policy", tokens: 1200, stable: true }, { id: "tools", label: "Tool schemas", tokens: 2100, stable: true }, { id: "examples", label: "Few-shot examples", tokens: 900, stable: true },
  { id: "timestamp", label: "Request timestamp", tokens: 24, stable: false }, { id: "profile", label: "Tenant profile", tokens: 480, stable: false }, { id: "query", label: "Current user query", tokens: 140, stable: false }, { id: "retrieval", label: "Retrieved evidence", tokens: 1800, stable: false },
];

export function PromptCacheWorkshopLab() {
  const [order, setOrder] = useState(CACHE_BLOCKS.map((b) => b.id)); const [boundary, setBoundary] = useState(2); const [runs, setRuns] = useState([]); const [tenantKey, setTenantKey] = useState(true);
  const blocks = order.map((id) => CACHE_BLOCKS.find((b) => b.id === id)); const prefix = blocks.slice(0, boundary + 1); const cached = prefix.every((b) => b.stable) ? prefix.reduce((s, b) => s + b.tokens, 0) : prefix.slice(0, prefix.findIndex((b) => !b.stable)).reduce((s, b) => s + b.tokens, 0); const total = blocks.reduce((s, b) => s + b.tokens, 0);
  const move = (i, d) => setOrder((o) => { const n = [...o], j = i + d; if (j < 0 || j >= n.length) return o; [n[i], n[j]] = [n[j], n[i]]; setRuns([]); return n; });
  const replay = () => setRuns(Array.from({ length: 5 }, (_, i) => ({ id: i + 1, cached: i === 0 ? 0 : cached, uncached: total - (i === 0 ? 0 : cached), latency: Math.round(820 - (i === 0 ? 0 : cached) / total * 430), safe: tenantKey })));
  const savings = runs.length ? Math.round(runs.slice(1).reduce((s, r) => s + r.cached, 0) / runs.reduce((s, r) => s + r.cached + r.uncached, 0) * 100) : 0;
  return <LabFrame number="19" kicker="Inference efficiency" title="Prompt Cache Workshop" subtitle="Build a Reusable Prefix" accent="#0369a1" soft="#eaf6ff" lead="Reorder real prompt blocks, place the cache boundary, and replay five requests to see prefix hits, misses, latency, and isolation risk." stats={[{ label: "Stable prefix", value: `${cached} tok` }, { label: "Savings", value: runs.length ? `${savings}%` : "—" }, { label: "Isolation", value: tenantKey ? "Keyed" : "Unsafe" }]}>
    <div className="lx-grid">
      <Panel title="Prompt block stack" subtitle="Stable blocks belong first"><div className="lx-pb lx-scroll">{blocks.map((b, i) => <div className={`lx-card ${!b.stable ? "bad" : ""}`} key={b.id}><div className="lx-row"><span className="lx-kbd">{i + 1}</span><Tag tone={b.stable ? "good" : "warn"}>{b.stable ? "stable" : "volatile"}</Tag><b className="lx-grow">{b.label}</b><Tag>{b.tokens}</Tag><Button small onClick={() => move(i, -1)}>↑</Button><Button small onClick={() => move(i, 1)}>↓</Button></div>{i === boundary && <button className="lx-callout" style={{ width: "100%", border: 0, marginTop: 7 }} onClick={() => setBoundary(Math.max(0, boundary - 1))}>Cache boundary after this block</button>}</div>)}<div className="lx-label">Boundary position · {boundary + 1}</div><input aria-label="Cache boundary" type="range" className="lx-range" min="0" max={blocks.length - 1} value={boundary} onChange={(e) => { setBoundary(Number(e.target.value)); setRuns([]); }} /></div></Panel>
      <Panel title="Cache waterfall" subtitle="Five requests share policy but change user data" action={<Button primary small onClick={replay}>Replay requests</Button>}><div className="lx-pb">{runs.length ? runs.map((r) => <div className="lx-card" key={r.id}><div className="lx-row"><Tag>R{r.id}</Tag><b className="lx-grow">{r.latency} ms</b><Tag tone={r.cached ? "good" : "warn"}>{r.cached ? `${r.cached} cached` : "cold"}</Tag></div><div style={{ display: "flex", height: 18, marginTop: 7, borderRadius: 5, overflow: "hidden" }}><span style={{ width: `${r.cached / total * 100}%`, background: "var(--good)" }} /><span style={{ width: `${r.uncached / total * 100}%`, background: "#f4b45d" }} /></div></div>) : <div className="lx-empty">Reorder the stack and replay requests.</div>}<div className="lx-row"><Tag tone="good">cached prefix</Tag><Tag tone="warn">uncached suffix</Tag></div></div></Panel>
      <Panel title="Cache controls" subtitle="Fast is not useful if boundaries leak"><div className="lx-pb"><button onClick={() => { setTenantKey((x) => !x); setRuns([]); }} className={`lx-card click ${tenantKey ? "good" : "bad"}`} style={{ width: "100%", textAlign: "left" }}><b>Tenant isolation key</b><p>{tenantKey ? "organization + project + model version" : "one global cache namespace"}</p></button><Meter label="Prefix reuse" value={cached / total * 100} /><Meter label="Projected latency reduction" value={cached / total * 72} /><div className={`lx-callout ${!tenantKey ? "bad" : prefix.some((b) => !b.stable) ? "bad" : cached > 3500 ? "good" : ""}`}>{!tenantKey ? "Cross-tenant cache identity can leak or misapply private context." : prefix.some((b) => !b.stable) ? "A volatile block sits inside the cache prefix. Every changed request invalidates blocks after it." : "The prefix is stable and isolated. Replay to measure the gain."}</div></div></Panel>
    </div>
  </LabFrame>;
}

/* ───────────────────────── 20 · Technique Architecture Studio ───────────────────────── */
const ARCH_SCENARIOS = [
  { id: "policy", label: "Private policy assistant", need: "Fresh documents, citations, read-only answers", ideal: { knowledge: "rag", behavior: "prompt", action: "none", safety: "eval" } },
  { id: "style", label: "Consistent support voice", need: "Stable nuanced behavior across high volume", ideal: { knowledge: "none", behavior: "tune", action: "none", safety: "eval" } },
  { id: "orders", label: "Order-management agent", need: "Live inventory, cancellations, policy, permission", ideal: { knowledge: "rag", behavior: "prompt", action: "tools", safety: "guard" } },
];
const TECH = [{ id: "prompt", label: "Prompt + examples", cost: 1, fresh: 60 }, { id: "rag", label: "RAG", cost: 3, fresh: 96 }, { id: "tune", label: "Fine-tune", cost: 8, fresh: 28 }, { id: "tools", label: "Authenticated tools", cost: 5, fresh: 100 }, { id: "guard", label: "Auth + guardrails", cost: 4, fresh: 88 }, { id: "eval", label: "Eval + abstention", cost: 2, fresh: 75 }, { id: "none", label: "No subsystem", cost: 0, fresh: 50 }];
const SLOTS = [{ id: "knowledge", label: "Knowledge plane" }, { id: "behavior", label: "Behavior plane" }, { id: "action", label: "Action plane" }, { id: "safety", label: "Safety plane" }];

export function TechniqueChooserLab() {
  const [scenarioId, setScenarioId] = useState("policy"); const [arch, setArch] = useState({ knowledge: "none", behavior: "prompt", action: "none", safety: "eval" }); const [activeTech, setActiveTech] = useState("rag"); const [tested, setTested] = useState(false);
  const scenario = ARCH_SCENARIOS.find((s) => s.id === scenarioId); const matches = SLOTS.map((s) => arch[s.id] === scenario.ideal[s.id]); const score = matches.filter(Boolean).length / 4 * 100; const cost = Object.values(arch).reduce((n, id) => n + TECH.find((t) => t.id === id).cost, 0); const freshness = Math.round(Object.values(arch).reduce((n, id) => n + TECH.find((t) => t.id === id).fresh, 0) / 4);
  const chooseScenario = (id) => { setScenarioId(id); setArch({ knowledge: "none", behavior: "prompt", action: "none", safety: "eval" }); setTested(false); };
  return <LabFrame number="20" kicker="System strategy" title="Fine-Tune, RAG, Prompt, or Tool?" subtitle="Architecture Composition Studio" accent="#475569" soft="#edf2f7" lead="Compose an AI system by placing techniques into knowledge, behavior, action, and safety planes. Then run requirement tests—not slogans." stats={[{ label: "Fit score", value: tested ? `${score}%` : "—" }, { label: "Complexity", value: cost }, { label: "Freshness", value: `${freshness}%` }]}>
    <div className="lx-grid">
      <Panel title="Product brief" subtitle="Requirements determine the architecture"><div className="lx-pb">{ARCH_SCENARIOS.map((s) => <button key={s.id} onClick={() => chooseScenario(s.id)} className={`lx-card click ${scenarioId === s.id ? "on" : ""}`} style={{ width: "100%", textAlign: "left" }}><b>{s.label}</b><p>{s.need}</p></button>)}<div className="lx-label">Technique palette</div><div className="lx-row wrap">{TECH.map((t) => <button key={t.id} onClick={() => setActiveTech(t.id)} className={`lx-token ${activeTech === t.id ? "on" : ""}`} style={activeTech === t.id ? { borderColor: "var(--a)", background: "var(--as)" } : undefined}>{t.label}</button>)}</div></div></Panel>
      <Panel title="Architecture canvas" subtitle="Select a technique, then place it in a plane" action={<Button primary small onClick={() => setTested(true)}>Run requirement tests</Button>}><div className="lx-pb" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>{SLOTS.map((slot, i) => { const t = TECH.find((x) => x.id === arch[slot.id]); return <button key={slot.id} onClick={() => { setArch((a) => ({ ...a, [slot.id]: activeTech })); setTested(false); }} className={`lx-drop ${tested ? matches[i] ? "good" : "bad" : ""}`} style={{ minHeight: 145, textAlign: "left", borderColor: tested ? matches[i] ? "var(--good)" : "var(--bad)" : undefined }}><Tag tone="a">{slot.label}</Tag><h3 style={{ margin: "18px 0 4px" }}>{t.label}</h3><p style={{ color: "var(--mut)", fontSize: 11 }}>Complexity {t.cost} · freshness {t.fresh}%</p>{tested && <Tag tone={matches[i] ? "good" : "bad"}>{matches[i] ? "requirement fit" : `expected ${TECH.find((x) => x.id === scenario.ideal[slot.id]).label}`}</Tag>}</button>; })}</div></Panel>
      <Panel title="Architecture review" subtitle="Every subsystem must earn its lifecycle cost"><div className="lx-pb"><Meter label="Requirement coverage" value={tested ? score : 0} /><Meter label="Freshness" value={freshness} /><Meter label="Simplicity" value={cap(100 - cost * 5)} /><div className="lx-label">Scenario tests</div>{[{ label: "Uses current private knowledge", slot: "knowledge" }, { label: "Produces required response behavior", slot: "behavior" }, { label: "Accesses or changes live state safely", slot: "action" }, { label: "Detects failures before users", slot: "safety" }].map((test, i) => <div className={`lx-card ${tested ? matches[i] ? "good" : "bad" : ""}`} key={test.label}><div className="lx-row"><Tag tone={tested ? matches[i] ? "good" : "bad" : ""}>T{i + 1}</Tag><b>{test.label}</b></div></div>)}{tested && <div className={`lx-callout ${score === 100 ? "good" : "bad"}`}>{score === 100 ? "Architecture passes all requirements with each technique in the correct role." : "The system is solving at least one requirement with the wrong adaptation mechanism."}</div>}</div></Panel>
    </div>
  </LabFrame>;
}
