import React from "react";

export const LAB_CSS = `
  :root{color-scheme:light}*{box-sizing:border-box}html,body,#root,#lab-root{margin:0;min-height:100%}body{background:#f4f6f8}button,input,select,textarea{font:inherit}button{cursor:pointer;touch-action:manipulation}
  .lx{--a:#635bff;--as:#efefff;--ink:#152033;--mut:#647084;--line:#dfe4eb;--panel:#fff;--bg:#f4f6f8;--good:#14805e;--bad:#c73d4d;--warn:#b96b16;min-height:100vh;min-height:100dvh;background:radial-gradient(circle at 92% 0,var(--as),transparent 25%),var(--bg);color:var(--ink);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;padding:18px}
  .lx-shell{max-width:1500px;margin:auto}.lx-head{display:flex;gap:20px;align-items:flex-start;margin-bottom:14px}.lx-kick{color:var(--a);font:800 10px/1.2 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}.lx h1{font-size:clamp(24px,3vw,38px);line-height:1;letter-spacing:-.045em;margin:7px 0 6px}.lx h1 span{font-weight:500;color:var(--mut)}.lx-lead{color:var(--mut);margin:0;max-width:820px}.lx-stats{margin-left:auto;display:flex;gap:8px}.lx-stat{min-width:86px;background:rgba(255,255,255,.88);border:1px solid var(--line);border-radius:11px;padding:8px 10px;text-align:right}.lx-stat span{display:block;color:var(--mut);font:700 8px/1.2 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.06em}.lx-stat b{display:block;font-size:18px;margin-top:2px;color:var(--a)}
  .lx-grid{display:grid;grid-template-columns:280px minmax(480px,1fr) 300px;gap:12px;align-items:start}.lx-grid.two{grid-template-columns:330px minmax(520px,1fr)}.lx-grid.wide{grid-template-columns:minmax(560px,1.45fr) minmax(300px,.75fr)}.lx-panel{background:var(--panel);border:1px solid var(--line);border-radius:13px;overflow:hidden;box-shadow:0 8px 26px rgba(24,36,58,.055)}.lx-ph{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 14px;border-bottom:1px solid var(--line);background:linear-gradient(120deg,#fff,var(--as))}.lx-ph h2{font-size:13px;margin:0}.lx-ph small{display:block;color:var(--mut);font-size:10px;margin-top:2px}.lx-pb{padding:12px 14px}.lx-scroll{max-height:520px;overflow:auto}
  .lx-btn{min-height:42px;border:1px solid var(--line);border-radius:9px;background:#fff;color:var(--ink);padding:8px 12px;font-weight:750;transition:.18s transform,.18s border-color,.18s background}.lx-btn:hover{transform:translateY(-1px);border-color:var(--a)}.lx-btn.primary{background:var(--a);border-color:var(--a);color:#fff;box-shadow:0 7px 16px color-mix(in srgb,var(--a) 22%,transparent)}.lx-btn.danger{color:var(--bad);border-color:#edc8ce;background:#fff7f8}.lx-btn.ghost{background:transparent}.lx-btn:disabled{opacity:.45;cursor:not-allowed;transform:none}.lx-btn.sm{min-height:34px;padding:5px 9px;font-size:11px}.lx-row{display:flex;gap:8px;align-items:center}.lx-row.wrap{flex-wrap:wrap}.lx-grow{flex:1}.lx-label{color:var(--mut);font:800 9px/1.2 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em;margin:10px 0 7px}.lx-label:first-child{margin-top:0}
  .lx-card{border:1px solid var(--line);border-radius:10px;background:#fff;padding:10px;margin-bottom:8px;transition:.18s border-color,.18s transform,.18s background}.lx-card.click{cursor:pointer}.lx-card.click:hover{transform:translateY(-1px);border-color:var(--a)}.lx-card.on{border-color:var(--a);background:var(--as);box-shadow:0 0 0 2px color-mix(in srgb,var(--a) 9%,transparent)}.lx-card.bad{border-color:#efc8cd;background:#fff7f8}.lx-card.good{border-color:#b9dfd2;background:#f3fbf8}.lx-card b{font-size:11.5px}.lx-card p{color:var(--mut);font-size:11px;margin:4px 0 0}.lx-tag{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:3px 7px;background:#f0f2f5;color:#4f5c70;font:750 9px/1.2 ui-monospace,monospace;text-transform:uppercase}.lx-tag.a{background:var(--as);color:var(--a)}.lx-tag.good{background:#eaf8f3;color:var(--good)}.lx-tag.bad{background:#fff0f2;color:var(--bad)}.lx-tag.warn{background:#fff6e8;color:var(--warn)}
  .lx-meter{height:7px;background:#edf0f4;border-radius:99px;overflow:hidden}.lx-meter>span{display:block;height:100%;background:var(--a);border-radius:inherit;transition:width .3s ease}.lx-metric{margin:9px 0}.lx-mtop{display:flex;justify-content:space-between;color:var(--mut);font-size:10px;margin-bottom:4px}.lx-mtop b{color:var(--ink);font-variant-numeric:tabular-nums}.lx-metrics{display:grid;grid-template-columns:1fr 1fr;gap:2px 14px}
  .lx-tabs{display:flex;gap:4px;border-bottom:1px solid var(--line);padding:7px}.lx-tab{min-height:34px;border:0;border-radius:7px;background:transparent;color:var(--mut);padding:6px 10px;font-size:11px;font-weight:750}.lx-tab.on{background:var(--as);color:var(--a)}
  .lx-console{background:#111823;color:#c7d4e6;border-radius:10px;padding:11px;font:10.5px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;min-height:120px;max-height:220px;overflow:auto}.lx-log{display:flex;gap:8px}.lx-log time{color:#66768c}.lx-log .ok{color:#62d5aa}.lx-log .err{color:#ff8290}.lx-log .info{color:#77b8ff}.lx-log .warn{color:#ffc56f}
  .lx-stage{position:relative;border:1px solid var(--line);border-radius:11px;background:linear-gradient(#fbfcfe,#f7f9fc);min-height:260px;padding:14px;overflow:hidden}.lx-node{position:absolute;min-width:104px;padding:9px 10px;border:1.5px solid #cdd4de;border-radius:10px;background:#fff;box-shadow:0 5px 14px rgba(29,43,66,.07);font-size:10px;text-align:center;transition:.25s border-color,.25s box-shadow,.25s transform}.lx-node b{display:block;font-size:11px}.lx-node.live{border-color:var(--a);box-shadow:0 0 0 3px color-mix(in srgb,var(--a) 12%,transparent),0 8px 20px rgba(29,43,66,.1);transform:translateY(-2px)}.lx-node.fail{border-color:var(--bad);background:#fff5f6}.lx-wire{position:absolute;height:2px;background:#ced5df;transform-origin:left center}.lx-pulse{position:absolute;width:9px;height:9px;border-radius:50%;background:var(--a);box-shadow:0 0 0 6px color-mix(in srgb,var(--a) 14%,transparent);transition:.35s left,.35s top}
  .lx-table{width:100%;border-collapse:collapse}.lx-table th{text-align:left;color:var(--mut);font:800 8px/1.2 ui-monospace,monospace;text-transform:uppercase;letter-spacing:.06em;padding:7px 8px;border-bottom:1px solid var(--line)}.lx-table td{font-size:10.5px;padding:8px;border-bottom:1px solid #edf0f4;vertical-align:top}.lx-table tr.click{cursor:pointer}.lx-table tr.click:hover{background:#f8f9fb}.lx-input,.lx-select,.lx-textarea{width:100%;border:1px solid #cfd6e0;border-radius:8px;background:#fff;color:var(--ink);padding:9px 10px}.lx-textarea{min-height:150px;resize:vertical;font:11px/1.55 ui-monospace,monospace}.lx-input:focus,.lx-select:focus,.lx-textarea:focus{outline:3px solid color-mix(in srgb,var(--a) 20%,transparent);border-color:var(--a)}.lx-range{width:100%;accent-color:var(--a)}
  .lx-token{display:inline-flex;align-items:center;gap:5px;border:1px solid var(--line);border-radius:7px;background:#fff;padding:6px 8px;font:700 10px/1.2 ui-monospace,monospace;cursor:grab}.lx-token:active{cursor:grabbing}.lx-drop{min-height:70px;border:1px dashed #bfc8d5;border-radius:9px;background:#fafbfc;padding:8px}.lx-drop.over{border-color:var(--a);background:var(--as)}
  .lx-callout{padding:10px 11px;border-radius:9px;background:var(--as);color:#38465a;font-size:11px}.lx-callout.bad{background:#fff0f2;color:#8e2d38}.lx-callout.good{background:#eaf8f3;color:#116046}.lx-divider{height:1px;background:var(--line);margin:11px 0}.lx-empty{padding:24px;text-align:center;color:var(--mut);font-size:11px}.lx-kbd{font:700 9px/1 ui-monospace,monospace;border:1px solid #cbd2dd;border-bottom-width:2px;border-radius:4px;padding:2px 4px;background:#fff}
  @keyframes lxblink{50%{opacity:.25}}.lx-running{animation:lxblink .8s ease-in-out infinite}.lx button:focus-visible,.lx [tabindex]:focus-visible{outline:3px solid color-mix(in srgb,var(--a) 27%,transparent);outline-offset:2px}
  @media(max-width:1100px){.lx-grid,.lx-grid.two,.lx-grid.wide{grid-template-columns:1fr 1fr}.lx-grid>.lx-panel:last-child{grid-column:1/-1}.lx-stats{flex-wrap:wrap}}
  @media(max-width:720px){.lx{padding:11px}.lx-head{display:block}.lx-stats{margin:10px 0 0}.lx-grid,.lx-grid.two,.lx-grid.wide{grid-template-columns:1fr}.lx-grid>.lx-panel:last-child{grid-column:auto}.lx-metrics{grid-template-columns:1fr}.lx-stage{min-height:320px}.lx h1 span{display:block;margin-top:5px}.lx-textarea{font-size:16px}.lx-btn.sm,.lx-tab{min-height:44px}.lx-card.click{min-height:44px}.lx-token:is(button){min-height:40px}}
  @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;

export function LabFrame({ number, kicker, title, subtitle, accent = "#635bff", soft = "#efefff", lead, stats = [], children }) {
  return <main className="lx" style={{ "--a": accent, "--as": soft }}><style>{LAB_CSS}</style><div className="lx-shell"><header className="lx-head"><div><div className="lx-kick">Lab {number} · {kicker}</div><h1>{title} <span>— {subtitle}</span></h1><p className="lx-lead">{lead}</p></div>{stats.length > 0 && <div className="lx-stats">{stats.map((s) => <div className="lx-stat" key={s.label}><span>{s.label}</span><b>{s.value}</b></div>)}</div>}</header>{children}</div></main>;
}

export function Panel({ title, subtitle, action, children, className = "" }) {
  return <section className={`lx-panel ${className}`}><div className="lx-ph"><div><h2>{title}</h2>{subtitle && <small>{subtitle}</small>}</div>{action}</div>{children}</section>;
}

export function Button({ children, primary, danger, ghost, small, className = "", ...props }) {
  return <button className={`lx-btn ${primary ? "primary" : ""} ${danger ? "danger" : ""} ${ghost ? "ghost" : ""} ${small ? "sm" : ""} ${className}`} {...props}>{children}</button>;
}

export function Meter({ label, value, suffix = "" }) {
  const safe = Math.max(0, Math.min(100, value));
  return <div className="lx-metric"><div className="lx-mtop"><span>{label}</span><b>{Math.round(value)}{suffix}</b></div><div className="lx-meter"><span style={{ width: `${safe}%`, background: safe < 45 ? "var(--bad)" : safe < 70 ? "var(--warn)" : "var(--good)" }} /></div></div>;
}

export function Tag({ children, tone = "" }) { return <span className={`lx-tag ${tone}`}>{children}</span>; }

export function Console({ lines = [] }) {
  return <div className="lx-console" aria-live="polite">{lines.map((line, i) => <div className="lx-log" key={`${line.text}-${i}`}><time>{String(i + 1).padStart(2, "0")}</time><span className={line.tone || "info"}>{line.text}</span></div>)}</div>;
}
