// Course map for the AI-ML Companion section.
//
// Generated by scripts/extract_aimlcompanion_catalog.mjs from the site mirror in
// aimlcompanion.ai/: track and module names come from each route's prerendered JSON-LD,
// the artwork from the og: images the site publishes for link previews. That is the whole
// of what is taken from the site. Lesson bodies are written locally per module (see
// lesson.js) rather than copied from aimlcompanion.ai, and every module also carries the
// deep link to its page on the site, which is where a subscriber reads the real thing.
import catalog from "../../data/aimlcompanion/catalog.json";

const files = import.meta.glob("../../assets/aimlcompanion/*.webp", { eager: true, import: "default" });
const byName = Object.fromEntries(
  Object.entries(files).map(([filePath, url]) => [filePath.split("/").pop(), url])
);

export const imageFor = (name) => (name ? byName[name] ?? null : null);

export const BASE = catalog.base;
export const TRACKS = catalog.tracks;
export const POSTS = catalog.posts;
export const PAGES = catalog.pages;
export const TOTALS = catalog.totals;

export const trackById = (id) => TRACKS.find(t => t.id === id) ?? null;
export const moduleIn = (track, moduleId) => {
  const index = track ? track.modules.findIndex(m => m.id === moduleId) : -1;
  return index === -1 ? null : { module: track.modules[index], index };
};

// One flat pass over tracks, modules and posts. The catalog is ~400 rows, so a plain
// substring scan is well inside the budget for a keystroke.
export function searchCatalog(query) {
  const q = query.trim().toLowerCase();
  if (!q) return null;
  const hit = (...fields) => fields.some(f => (f || "").toLowerCase().includes(q));

  const tracks = TRACKS.filter(t => hit(t.label, t.summary));
  const modules = [];
  for (const track of TRACKS) {
    for (const mod of track.modules) {
      if (hit(mod.label, mod.tagline)) modules.push({ ...mod, track });
    }
  }
  const posts = POSTS.filter(p => hit(p.label, p.summary, p.tags.join(" ")));
  return { query: q, tracks, modules, posts, total: tracks.length + modules.length + posts.length };
}
