// The DSA practice set: Code Lab problems merged with the takeUforward scrape.
// Generated by scripts/build_tuf_practice.py — rerun it after the scrape grows.
import index from "../../../data/practice/index.json";
import sheetData from "../../../data/practice/sheets.json";

export const practiceProblems = index.problems || [];
export const practiceCounts = index.counts || {};
export const practiceTopics = index.topics || [];
export const practiceById = new Map(practiceProblems.map((problem) => [problem.id, problem]));
export const sheets = sheetData.sheets || [];
export const sheetById = new Map(sheets.map((sheet) => [sheet.id, sheet]));

export const LEVELS = ["Basic", "Core", "Pro"];

/** Every practice item of a sheet, in order, with the step and section it sits in. */
export function sheetItems(sheet) {
  const items = [];
  const walk = (nodes, path) => nodes.forEach((node) => {
    if (node.children) walk(node.children, [...path, node.title]);
    else if (node.kind === "practice") items.push({ ...node, step: path[0], section: path[path.length - 1] });
  });
  walk(sheet?.steps || [], []);
  return items;
}

const detailCache = new Map();

/**
 * Per-problem extras (statement for tuf-only problems, "Now Your Turn", fun
 * facts, doubts, follow-ups, peer solutions, reference solution). Fetched on
 * open; concurrent callers share one request. Resolves to null when a problem
 * has none.
 */
export function loadPracticeDetail(id) {
  const problem = practiceById.get(id);
  if (!problem?.extras) return Promise.resolve(null);
  if (detailCache.has(id)) return detailCache.get(id);
  const request = fetch(`/practice/problems/${encodeURIComponent(id)}.json`)
    .then((response) => {
      if (!response.ok) throw new Error(`Could not load this problem (HTTP ${response.status}).`);
      return response.json();
    })
    .catch((error) => {
      detailCache.delete(id);
      throw error;
    });
  detailCache.set(id, request);
  return request;
}

/** Code Lab difficulty words for rows that only carry tuf's Basic/Core/Pro. */
export const codelabDifficulty = (level) => ({ Basic: "Easy", Core: "Medium", Pro: "Hard" }[level] || level);
